Repository vesoft-inc/nebula-graph, pull requests merged in 2020-12, with the labels that each got.

#444 Fix action docker-storage failed
  .github/workflows/release.yml
Labels: ready-for-testing

#426 Check remove host no duplicate
  src/validator/BalanceValidator.cpp
Labels: ready-for-testing

#442 print NEBULA_COMMON_REPO_TAG
  cmake/FetchModule.cmake
Labels: ready-for-testing

#446 Fix filter bug
  src/executor/query/FilterExecutor.cpp
  tests/query/v1/test_go.py
Labels: ready-for-testing

#451 add path outputs_ & test case
  src/planner/planners/SequentialPlanner.cpp
  src/validator/FindPathValidator.cpp
  tests/query/v1/test_find_path.py
Labels: ready-for-testing

#452 apply propIter to Join
  src/context/Iterator.cpp
  src/context/Iterator.h
  src/executor/query/DataJoinExecutor.cpp
  tests/query/v1/test_fetch_vertex.py
Labels: ready-for-testing

#454 fix ErrorCode typo
  src/service/GraphService.cpp
  src/service/QueryInstance.cpp
  tests/common/nebula_test_suite.py
Labels: ready-for-testing

#459 Sort path result
  src/validator/FindPathValidator.cpp
  tests/query/v1/test_find_path.py
Labels: doc required, ready-for-testing

#456 Add BitOp tests
  tests/query/v1/test_groupby.py
Labels: ready-for-testing

#462 Modify container name
  tests/common/utils.py
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#458 Optimize index scan '!=' and 'logic or'
  src/optimizer/rule/IndexScanRule.cpp
  src/optimizer/rule/IndexScanRule.h
Labels: ready-for-testing

#450 Fix get error_code
  tests/common/nebula_test_suite.py
  tests/maintain/test_index.py
Labels: ready-for-testing

#437 let "show hosts" can show git info sha of graph/meta/storage
  src/executor/admin/ShowHostsExecutor.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/planner/Admin.h
  src/service/QueryEngine.cpp
  src/validator/AdminValidator.cpp
Labels: doc required, ready-for-testing

#447 Replace behave framework with pytest-bdd and add DataSetComparator
  .github/workflows/pull_request.yml
  CMakeLists.txt
  ci/test.sh
  tests/.gitignore
  tests/admin/test_permission.py
  tests/admin/test_space.py
  tests/admin/test_users.py
  tests/common/csv_import.py
  tests/common/global_data_loader.py
  tests/common/nebula_service.py
  tests/common/nebula_test_suite.py
  tests/common/types.py
  tests/conftest.py
  tests/data/nba/bachelor.csv
  tests/data/nba/like.csv
  tests/data/nba/player.csv
  tests/data/nba/schema.ngql
  tests/data/nba/serve.csv
  tests/data/nba/team.csv
  tests/data/nba/teammate.csv
  tests/data/student/is_colleagues.csv
  tests/data/student/is_friend.csv
  tests/data/student/is_schoolmate.csv
  tests/data/student/is_teacher.csv
  tests/data/student/person.csv
  tests/data/student/schema.ngql
  tests/data/student/student.csv
  tests/data/student/teacher.csv
  tests/maintain/test_index.py
  tests/mutate/test_delete_edges_2.py
  tests/pytest.ini
  tests/query/stateless/test_go.py
  tests/query/stateless/test_schema.py
  tests/query/v1/test_fetch_edges.py
  tests/query/v1/test_find_path.py
  tests/query/v2/conftest.py
  tests/requirements.txt
  tests/tck/__init__.py
  tests/tck/conftest.py
  tests/tck/features/job/job.feature
  tests/tck/features/job/snapshot.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/VariableLengthRelationship.feature
  tests/tck/features/parser/nebula.feature
  tests/tck/features/utils.feature
  tests/tck/steps/__init__.py
  tests/tck/steps/environment.py
  tests/tck/steps/test_value_parser.py
  tests/tck/steps/value-parsing.py
  tests/tck/utils/__init__.py
  tests/tck/utils/comparator.py
  tests/tck/utils/nbv.py
  tests/tck/utils/table.py
Labels: in progress, ready-for-testing

#466 Add gherkin format tool to unify feature files code style
  .github/workflows/pull_request.yml
  .gitignore
  tests/.gitignore
  tests/Makefile
  tests/query/v1/test_find_path.py
  tests/tck/features/job/job.feature
  tests/tck/features/job/snapshot.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/VariableLengthRelationship.feature
  tests/tck/features/parser/nebula.feature
Labels: ready-for-testing

#469 Correct print the property type.
  src/parser/MaintainSentences.cpp
Labels: ready-for-testing

#468 change docker image tag
  .github/workflows/docker.yml
Labels: ready-for-testing

#464 Path bidirection
  src/executor/algo/CartesianProductExecutor.cpp
  src/executor/algo/ConjunctPathExecutor.cpp
  src/executor/algo/ProduceAllPathsExecutor.cpp
  src/validator/FindPathValidator.cpp
  src/validator/FindPathValidator.h
  src/validator/test/FindPathValidatorTest.cpp
  tests/query/v1/test_find_path.py
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/ShortestPath.feature
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#471 Remove unnecessary unreserved key words.
  src/parser/parser.yy
Labels: ready-for-testing

#461 support path without loop
  src/executor/algo/ConjunctPathExecutor.cpp
  src/executor/algo/ConjunctPathExecutor.h
  src/executor/algo/ProduceAllPathsExecutor.cpp
  src/executor/algo/ProduceAllPathsExecutor.h
  src/executor/algo/ProduceSemiShortestPathExecutor.cpp
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/planner/Algo.h
  src/validator/FindPathValidator.cpp
  src/validator/FindPathValidator.h
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/PathWithoutSameVertices.feature
Labels: ready-for-testing

#455 Fit the new storage queyr interface.
  ci/test.sh
  src/context/ast/QueryAstContext.h
  src/executor/query/IndexScanExecutor.cpp
  src/planner/PlanNode.h
  src/planner/match/Expand.cpp
  src/planner/match/Expand.h
  src/planner/match/PropIndexSeek.cpp
  src/validator/AssignmentValidator.cpp
  src/validator/FindPathValidator.cpp
  src/validator/GetSubgraphValidator.cpp
  src/validator/GetSubgraphValidator.h
  src/validator/IndexScanValidator.cpp
  src/validator/IndexScanValidator.h
  src/validator/test/MockSchemaManager.h
  tests/maintain/test_index.py
Labels: ready-for-testing

#473 delete path pytest
  tests/query/v1/test_find_path.py
Labels: ready-for-testing

#478 Migrate variable length match test cases
  .github/workflows/pull_request.yml
  ci/test.sh
  tests/Makefile
  tests/conftest.py
  tests/query/v2/match/test_variable_length_relationships.py
  tests/tck/conftest.py
  tests/tck/features/match/VariableLengthRelationship.feature
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#465 expand logic expression for index scan
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/util/test/ExpressionUtilsTest.cpp
  src/validator/IndexScanValidator.cpp
Labels: ready-for-testing

#483 Support regex pattern in CI
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#475 Support csv data load steps for bdd test framework
  .gitignore
  tests/.gitignore
  tests/common/comparator.py
  tests/common/configs.py
  tests/common/nebula_service.py
  tests/common/types.py
  tests/common/utils.py
  tests/conftest.py
  tests/data/nba/schema.ngql
  tests/data/student/schema.ngql
  tests/tck/conftest.py
  tests/tck/features/expression/Yield.feature
  tests/tck/features/job/job.feature
  tests/tck/features/job/snapshot.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/parser/Space.feature
  tests/tck/utils/table.py
  tests/tck/utils/utils.py
Labels: ready-for-testing

#482 improve show hosts from chaos test
  src/executor/admin/ShowHostsExecutor.cpp
Labels: ready-for-testing

#493 Support to import int data in test framework
  .gitignore
  tests/common/csv_import.py
  tests/common/types.py
  tests/common/utils.py
  tests/data/nba/config.yaml
  tests/data/nba/schema.ngql
  tests/data/nba_int_vid/config.yaml
  tests/data/student/config.yaml
  tests/data/student/schema.ngql
  tests/requirements.txt
  tests/tck/conftest.py
  tests/tck/features/parser/Example.feature
Labels: ready-for-testing

#474 Choose default port numbers to reduce chances of conflicts
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
Labels: doc required, ready-for-testing

#494 Fix the issue that some job don't require space.
  .github/workflows/pull_request.yml
  src/validator/AdminJobValidator.cpp
  src/validator/AdminJobValidator.h
  tests/Makefile
Labels: ready-for-testing

#497 Refactor Value comparator and support regex match in expected results
  tests/common/comparator.py
  tests/common/dataset_printer.py
  tests/conftest.py
  tests/tck/conftest.py
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/parser/Example.feature
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/PathWithoutSameVertices.feature
  tests/tck/features/path/ShortestPath.feature
  tests/tck/utils/nbv.py
  tests/tck/utils/table.py
Labels: ready-for-testing

#506 add go tck test
  tests/query/v1/test_go.py
  tests/tck/conftest.py
  tests/tck/features/go/go.feature
  tests/tck/features/go/go.intVid.feature
Labels: ready-for-testing

#509 CI added support to specify int and hash as vid
  tests/Makefile
  tests/tck/utils/mmh2.py
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#512 fix CartesianProduct addVar bug
  src/planner/Algo.cpp
Labels: ready-for-testing

#515 Fix graph compile.
  src/service/GraphService.cpp
Labels: ready-for-testing

#513 Remove the bind of meta client of interface of manager.
  src/service/QueryEngine.cpp
Labels: ready-for-testing

#507 Support more features in test framework
  tests/CMakeLists.txt
  tests/Makefile
  tests/common/comparator.py
  tests/common/dataset_printer.py
  tests/common/nebula_service.py
  tests/common/types.py
  tests/common/utils.py
  tests/conftest.py
  tests/ntr.out-of-source
  tests/tck/conftest.py
  tests/tck/features/parser/Example.feature
  tests/tck/utils/mmh2.py
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#504 fix RewriteMatchLabelVisitor::rewriteExprList bug
  src/visitor/RewriteMatchLabelVisitor.cpp
Labels: ready-for-testing

#484 add algo explain
  src/planner/Algo.cpp
  src/planner/Algo.h
Labels: ready-for-testing

#470 Add session 0 processing
  src/service/GraphService.cpp
Labels: ready-for-testing

#510 add subgraph tck case string & integer vid
  tests/tck/features/subgraph/subgraph.feature
  tests/tck/features/subgraph/subgraph.intVid.feature
Labels: ready-for-testing

#511 add path integer vid tck test
  tests/tck/features/path/AllPath.intVid.feature
  tests/tck/features/path/NoLoop.feature
  tests/tck/features/path/NoLoop.intVid.feature
  tests/tck/features/path/ShortestPath.intVid.feature
Labels: ready-for-testing

#480 Fix some issue about lookup the yield and the outputs.
  src/parser/Clauses.h
  src/validator/CMakeLists.txt
  src/validator/LookupValidator.cpp
  src/validator/LookupValidator.h
  src/validator/Validator.cpp
  src/validator/test/CMakeLists.txt
  src/validator/test/LookupValidatorTest.cpp
  tests/data/nba/config.yaml
  tests/data/nba_int_vid/config.yaml
  tests/query/stateless/test_lookup.py
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/Output.feature
  tests/tck/features/lookup/WithYield.feature
Labels: bug, doc required, ready-for-testing

#518 Set test move to tck.
  tests/tck/features/expression/Yield.feature
  tests/tck/features/go/go.IntVid.feature
  tests/tck/features/go/go.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/parser/Example.feature
  tests/tck/features/parser/nebula.feature
  tests/tck/features/path/AllPath.IntVid.feature
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/NoLoop.IntVid.feature
  tests/tck/features/path/NoLoop.feature
  tests/tck/features/path/ShortestPath.IntVid.feature
  tests/tck/features/path/ShortestPath.feature
  tests/tck/features/set/Set.IntVid.feature
  tests/tck/features/set/Set.feature
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing

#520 Support define some list variables used in expect result
  tests/common/utils.py
  tests/tck/conftest.py
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
  tests/tck/utils/table.py
Labels: ready-for-testing

#516 fix pr #494
  src/validator/AdminJobValidator.cpp
  src/validator/AdminJobValidator.h
Labels: ready-for-testing

#499 move 1.x lookup cases to tck
  tests/tck/features/index/Index.feature
  tests/tck/features/loopup/LookUp.feature
Labels: ready-for-testing

#524 move 1.x fetch str/id vertices/edges cases to tck
  tests/tck/features/fetch/FetchEdges.intVid.feature
  tests/tck/features/fetch/FetchEdges.strVid.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
Labels: ready-for-testing

#496 Support integer
  src/context/Iterator.cpp
  src/executor/algo/ConjunctPathExecutor.cpp
  src/executor/query/DataCollectExecutor.cpp
  src/executor/test/DataCollectTest.cpp
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/parser.yy
  src/planner/Mutate.cpp
  src/planner/Mutate.h
  src/util/SchemaUtil.cpp
  src/util/SchemaUtil.h
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchVerticesValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/LookupValidator.cpp
  src/validator/MutateValidator.cpp
  src/validator/MutateValidator.h
  src/validator/Validator.cpp
  src/validator/Validator.h
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/DeduceTypeVisitor.h
  tests/common/comparator.py
  tests/common/utils.py
  tests/conftest.py
  tests/query/v1/test_set.py
  tests/query/v2/conftest.py
  tests/query/v2/test_get_subgraph.py
  tests/tck/conftest.py
  tests/tck/features/fetch/FetchEdges.intVid.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/go/go.IntVid.feature
  tests/tck/features/go/go.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/lookup/Output.feature
  tests/tck/features/match/VariableLengthPattern.intVid.feature
  tests/tck/features/path/AllPath.IntVid.feature
  tests/tck/features/path/NoLoop.IntVid.feature
  tests/tck/features/path/ShortestPath.IntVid.feature
  tests/tck/features/set/Set.IntVid.feature
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#508 do not skip test_index.py
  tests/maintain/test_index.py
Labels: ready-for-testing

#529 The compaction and flush job need space too.
  src/validator/AdminJobValidator.h
  tests/tck/features/job/SpaceRequire.feature
Labels: ready-for-testing

#522 Fix same column expect result issue
  tests/Makefile
  tests/pytest.ini
  tests/query/v2/test_explain.py
  tests/tck/conftest.py
  tests/tck/features/explain/ExplainAndProfile.feature
  tests/tck/features/fetch/FetchEdges.intVid.feature
  tests/tck/features/fetch/FetchEdges.strVid.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/lookup/Output.feature
  tests/tck/features/lookup/WithYield.feature
  tests/tck/features/parser/Example.feature
  tests/tck/features/parser/nebula.feature
  tests/tck/features/path/AllPath.IntVid.feature
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/NoLoop.IntVid.feature
  tests/tck/features/path/NoLoop.feature
  tests/tck/features/path/ShortestPath.IntVid.feature
  tests/tck/features/path/ShortestPath.feature
  tests/tck/features/set/Set.IntVid.feature
  tests/tck/features/set/Set.feature
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/yield/Yield.feature
  tests/tck/steps/conftest.py
  tests/tck/steps/test_tck.py
  tests/tck/steps/test_value_parser.py
  tests/tck/utils/table.py
Labels: ready-for-testing

#501 modify match planner to support tag filter
  src/planner/match/Expand.cpp
  src/planner/match/MatchClausePlanner.cpp
  src/validator/MatchValidator.cpp
  src/validator/MatchValidator.h
  tests/common/comparator.py
  tests/tck/features/match/Base.feature
Labels: ready-for-testing

#517 Fix the bug of datetime default value eval in metad which don't initi…
  tests/tck/features/bugfix/TimeDefaultValue.feature
Labels: bug, ready-for-testing

#533 match by id tck
  tests/common/comparator.py
  tests/common/dataset_printer.py
  tests/query/v2/match/test_match_by_id.py
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/MatchById.intVid.feature
Labels: ready-for-testing

#531 Correct the filter not clone issue.
  src/planner/PlanNode.h
  src/planner/Query.cpp
  src/planner/Query.h
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
Labels: bug, ready-for-testing

#481 fix yield running constrain
  src/validator/YieldValidator.cpp
  src/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/yield/NoSpaceChosen.feature
  tests/tck/features/yield/Yield.feature
Labels: ready-for-testing

#514 Fix time value can't set null
  src/executor/QueryStorageExecutor.h
  src/util/SchemaUtil.cpp
  src/util/SchemaUtil.h
  src/validator/MutateValidator.cpp
  tests/mutate/test_insert_2.py
  tests/tck/features/mutate/InsertWithTimeType.feature
Labels: ready-for-testing

#523 added DCHECK for mothod expandExpr
  src/util/ExpressionUtils.cpp
Labels: ready-for-testing

#537 Delete unuse obj
  src/context/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/executor/test/CMakeLists.txt
  src/optimizer/test/CMakeLists.txt
  src/parser/test/CMakeLists.txt
  src/planner/test/CMakeLists.txt
  src/util/SchemaUtil.cpp
  src/util/test/CMakeLists.txt
  src/validator/test/CMakeLists.txt
  src/visitor/test/CMakeLists.txt
  tests/maintain/test_index.py
  tests/mutate/test_insert_1.py
  tests/tck/features/index/Index.feature
  tests/tck/features/mutate/InsertWithTimeType.feature
Labels: ready-for-testing

#448 Add list comprehension expression
  src/parser/GQLParser.h
  src/parser/parser.yy
  src/service/QueryInstance.cpp
  src/util/ParserUtil.h
  src/visitor/CollectAllExprsVisitor.cpp
  src/visitor/CollectAllExprsVisitor.h
  src/visitor/DeducePropsVisitor.cpp
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/DeduceTypeVisitor.h
  src/visitor/ExprVisitorImpl.cpp
  src/visitor/ExprVisitorImpl.h
  src/visitor/ExtractPropExprVisitor.cpp
  src/visitor/FindAnyExprVisitor.cpp
  src/visitor/FindAnyExprVisitor.h
  src/visitor/FoldConstantExprVisitor.cpp
  src/visitor/FoldConstantExprVisitor.h
  src/visitor/RewriteInputPropVisitor.cpp
  src/visitor/RewriteInputPropVisitor.h
  src/visitor/RewriteLabelAttrVisitor.cpp
  src/visitor/RewriteLabelAttrVisitor.h
  src/visitor/RewriteMatchLabelVisitor.cpp
  src/visitor/RewriteMatchLabelVisitor.h
  src/visitor/RewriteSymExprVisitor.cpp
  src/visitor/RewriteSymExprVisitor.h
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/yield/NoSpaceChosen.feature
Labels: doc required, ready-for-testing

#526 [testcase] Move mutate test to tck and add int vid test of mutate
  src/executor/QueryStorageExecutor.h
  src/parser/parser.yy
  tests/mutate/__init__.py
  tests/mutate/test_delete_edges.py
  tests/mutate/test_delete_edges_2.py
  tests/mutate/test_delete_vertices.py
  tests/mutate/test_delete_vertices_2.py
  tests/mutate/test_update_upsert.py
  tests/mutate/test_update_upsert_2.py
  tests/tck/features/delete/DeleteEdge.IntVid.feature
  tests/tck/features/delete/DeleteEdge.feature
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/delete/DeleteVertex.feature
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/update/Update.IntVid.feature
  tests/tck/features/update/Update.feature
Labels: ready-for-testing

#525 [testcase] add user test cases
  tests/tck/features/user/User.feature
Labels: ready-for-testing

#505 Match start from any node.
  src/context/Iterator.cpp
  src/context/ast/QueryAstContext.h
  src/executor/query/ProjectExecutor.cpp
  src/planner/match/AddDependencyStrategy.h
  src/planner/match/AddInputStrategy.h
  src/planner/match/Expand.cpp
  src/planner/match/Expand.h
  src/planner/match/InnerJoinStrategy.cpp
  src/planner/match/InnerJoinStrategy.h
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/MatchClausePlanner.h
  src/planner/match/MatchSolver.cpp
  src/planner/match/MatchSolver.h
  src/planner/match/PropIndexSeek.cpp
  src/planner/match/SegmentsConnectStrategy.h
  src/planner/match/SegmentsConnector.cpp
  src/planner/match/SegmentsConnector.h
  src/planner/match/VertexIdSeek.cpp
  src/validator/MatchValidator.cpp
  src/validator/test/QueryValidatorTest.cpp
  tests/tck/features/bugfix/MatchNotFilterTheUndeclaredTag.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/StartFromAnyNode.IntVid.feature
  tests/tck/features/match/StartFromAnyNode.feature
Labels: doc required, ready-for-testing

#540 Update the logical of cloud auth.
  src/service/PermissionManager.cpp
  src/service/Session.h
Labels: ready-for-review, ready-for-testing

#485 Match by tag index.
  src/context/ast/QueryAstContext.h
  src/planner/CMakeLists.txt
  src/planner/PlannersRegister.cpp
  src/planner/match/LabelIndexSeek.cpp
  src/planner/match/LabelIndexSeek.h
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/TagIndexSeek.h
  src/validator/test/CMakeLists.txt
  src/validator/test/MatchValidatorTest.cpp
  src/validator/test/MockIndexManager.cpp
  src/validator/test/MockIndexManager.h
  src/validator/test/MockSchemaManager.cpp
  src/validator/test/ValidatorTestBase.h
  tests/data/nba/config.yaml
  tests/data/nba_int_vid/config.yaml
  tests/query/v2/match/test_match_base.py
  tests/tck/features/match/SeekByTag.feature
Labels: doc required, ready-for-testing

#545 Fix the compiling
  src/validator/test/MockSchemaManager.h
Labels: ready-for-testing

#530 [testcase] Move Orderby cases to tck
  tests/query/v1/test_orderby.py
  tests/tck/features/go/Orderby.feature
Labels: ready-for-testing

#535 [testcase] yield tck test cases
  .gitignore
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: ready-for-testing

#543 [test cases]Add some cases for int vid lookup.
  src/validator/LookupValidator.cpp
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/Output.intVid.feature
  tests/tck/features/lookup/WithYield.intVid.feature
Labels: bug, ready-for-review, ready-for-testing

#546 Fix yield.
  src/executor/query/ProjectExecutor.cpp
  src/validator/YieldValidator.cpp
  src/validator/YieldValidator.h
  tests/admin/test_configs.py
  tests/tck/features/bugfix/TestYieldConstantAfterPipe.feature
Labels: bug, ready-for-testing

#547 Add version configurations
  CMakeLists.txt
  cmake/ConfigNebulaStorage.cmake
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  src/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/daemons/GraphDaemon.cpp
  src/planner/test/CMakeLists.txt
  src/service/QueryEngine.cpp
  src/version/CMakeLists.txt
  src/version/Version.cpp.in
  src/version/Version.h
Labels: ready-for-testing

#536 Enable push-down int vid computation case.
  tests/tck/features/go/GO.IntVid.feature
Labels: ready-for-testing

#430 toss
  src/executor/mutate/InsertExecutor.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/planner/Mutate.h
  src/validator/AdminValidator.cpp
  src/validator/MutateValidator.cpp
Labels: ready-for-testing
