Repository vesoft-inc/nebula-graph, pull requests merged in 2020-09, with the labels that each got.

#235 Executor and Planner for IndexScan
  src/executor/CMakeLists.txt
  src/executor/query/IndexScanExecutor.cpp
  src/executor/query/IndexScanExecutor.h
  src/planner/Query.h
Labels: in progress, ready-for-testing

#251 Let fetch vertices accept multi-vertices and input as vids when not specify tag.
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/validator/test/FetchVerticesTest.cpp
  tests/query/v1/test_fetch_vertex.py
Labels: ready-for-testing

#248 Refactor expression access with visitor pattern
  .github/workflows/pull_request.yml
  ci/test.sh
  src/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/executor/logic/test/CMakeLists.txt
  src/executor/query/test/CMakeLists.txt
  src/validator/Validator.cpp
  src/validator/test/CMakeLists.txt
  src/visitor/CMakeLists.txt
  src/visitor/EvaluableExprVisitor.h
  src/visitor/ExprVisitorImpl.cpp
  src/visitor/ExprVisitorImpl.h
  tests/common/nebula_service.py
  tests/requirements.txt
Labels: ready-for-testing

#252 Add operator() for expression context.
  src/context/QueryExpressionContext.h
  src/context/test/ExpressionContextTest.cpp
  src/executor/logic/LoopExecutor.cpp
  src/executor/logic/SelectExecutor.cpp
  src/executor/mutate/DeleteExecutor.cpp
  src/executor/query/AggregateExecutor.cpp
  src/executor/query/DataJoinExecutor.cpp
  src/executor/query/DedupExecutor.cpp
  src/executor/query/FilterExecutor.cpp
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetVerticesExecutor.cpp
  src/executor/query/LimitExecutor.cpp
  src/executor/query/ProjectExecutor.cpp
  src/executor/query/SortExecutor.cpp
  src/parser/MaintainSentences.h
  src/util/SchemaUtil.cpp
  src/validator/AdminValidator.cpp
  src/validator/TraversalValidator.cpp
  src/validator/Validator.cpp
Labels: ready-for-testing

#232 Set the get vertices/edges response columns name by plan. Change _vid…
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/GetPropExecutor.h
  src/executor/query/GetVerticesExecutor.cpp
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchEdgesValidator.h
  src/validator/FetchVerticesValidator.cpp
  src/validator/FetchVerticesValidator.h
  src/validator/GoValidator.h
  src/validator/test/FetchEdgesTest.cpp
  src/validator/test/FetchVerticesTest.cpp
  tests/query/v1/test_fetch_vertex.py
Labels: ready-for-testing

#253 Use expression visitor for expression type/props deduction
  src/mock/test/CMakeLists.txt
  src/planner/test/CMakeLists.txt
  src/validator/CMakeLists.txt
  src/validator/ExpressionProps.cpp
  src/validator/ExpressionProps.h
  src/validator/MutateValidator.h
  src/validator/Validator.cpp
  src/validator/Validator.h
  src/visitor/CMakeLists.txt
  src/visitor/DeducePropsVisitor.cpp
  src/visitor/DeducePropsVisitor.h
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/DeduceTypeVisitor.h
  src/visitor/EvaluableExprVisitor.h
  tests/common/nebula_service.py
Labels: ready-for-testing

#249 Merge all executor tests
  src/executor/CMakeLists.txt
  src/executor/logic/test/CMakeLists.txt
  src/executor/test/AggregateTest.cpp
  src/executor/test/CMakeLists.txt
  src/executor/test/DataCollectTest.cpp
  src/executor/test/DataJoinTest.cpp
  src/executor/test/DedupTest.cpp
  src/executor/test/FilterTest.cpp
  src/executor/test/GetNeighborsTest.cpp
  src/executor/test/LimitTest.cpp
  src/executor/test/LogicExecutorsTest.cpp
  src/executor/test/ProjectTest.cpp
  src/executor/test/QueryTestBase.h
  src/executor/test/SetExecutorTest.cpp
  src/executor/test/SortTest.cpp
Labels: ready-for-testing

#245 Find path validator.
  src/parser/parser.yy
  src/validator/CMakeLists.txt
  src/validator/FindPathValidator.cpp
  src/validator/FindPathValidator.h
  src/validator/GetSubgraphValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/GoValidator.h
  src/validator/TraversalValidator.cpp
  src/validator/TraversalValidator.h
  src/validator/Validator.cpp
  src/validator/test/QueryValidatorTest.cpp
Labels: ready-for-testing

#236 Add detect service is ok and init configs
  ci/test.sh
  src/CMakeLists.txt
  src/mock/MetaCache.cpp
  tests/admin/test_parts.py
  tests/common/configs.py
  tests/common/load_test_data.py
  tests/common/nebula_service.py
  tests/common/nebula_test_suite.py
  tests/conftest.py
  tests/nebula-test-run.py
  tests/query/stateless/test_if_exists.py
  tests/query/stateless/test_keyword.py
Labels: ready-for-testing

#258 Profile all test cases
  .github/workflows/pull_request.yml
  ci/test.sh
  src/validator/ExplainValidator.cpp
  src/validator/Validator.cpp
  src/validator/Validator.h
  tests/admin/__init__.py
  tests/admin/test_parts.py
  tests/bench/__init__.py
  tests/common/nebula_test_suite.py
  tests/maintain/__init__.py
  tests/mutate/__init__.py
  tests/query/__init__.py
  tests/query/bugs/__init__.py
  tests/query/stateless/__init__.py
  tests/query/stateless/test_yield.py
  tests/query/v1/__init__.py
  tests/query/v1/test_go.py
  tests/query/v1/test_groupby.py
  tests/query/v1/test_yield.py
  tests/query/v2/__init__.py
  tests/query/v2/test_explain.py
  tests/requirements.txt
Labels: ready-for-testing

#231 Subgraph
  src/context/Iterator.cpp
  src/context/test/IteratorTest.cpp
  src/executor/query/DataCollectExecutor.cpp
  src/validator/GetSubgraphValidator.cpp
  src/validator/GetSubgraphValidator.h
  src/validator/TraversalValidator.cpp
  src/validator/TraversalValidator.h
  src/validator/test/GetSubgraphValidatorTest.cpp
  tests/common/load_test_data.py
  tests/common/nebula_test_suite.py
  tests/data/nba.ngql
  tests/query/v1/test_go.py
  tests/query/v1/test_groupby.py
  tests/query/v2/test_get_subgraph.py
Labels: ready-for-testing

#255 Split the prepare properties to independent function for more readable.
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchEdgesValidator.h
  src/validator/FetchVerticesValidator.cpp
  src/validator/FetchVerticesValidator.h
Labels: ready-for-testing

#259 Add rewrite label attr expr visitor
  src/util/ExpressionUtils.h
  src/util/test/CMakeLists.txt
  src/util/test/ExpressionUtilsTest.cpp
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchVerticesValidator.cpp
  src/visitor/CMakeLists.txt
  src/visitor/CollectAllExprsVisitor.cpp
  src/visitor/CollectAllExprsVisitor.h
  src/visitor/FindAnyExprVisitor.cpp
  src/visitor/FindAnyExprVisitor.h
  src/visitor/RewriteLabelAttrVisitor.cpp
  src/visitor/RewriteLabelAttrVisitor.h
Labels: ready-for-testing

#254 Add the ownership holder to separate the logic of ownership and conta…
  src/util/ObjectPool.h
Labels: ready-for-testing

#261 Add QueryStorageExecutor to extract the code to handle completeness f…
  src/executor/QueryStorageExecutor.h
  src/executor/mutate/DeleteExecutor.cpp
  src/executor/mutate/DeleteExecutor.h
  src/executor/mutate/InsertExecutor.cpp
  src/executor/mutate/InsertExecutor.h
  src/executor/mutate/UpdateExecutor.h
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetNeighborsExecutor.h
  src/executor/query/GetPropExecutor.h
  src/executor/query/IndexScanExecutor.cpp
  src/executor/query/IndexScanExecutor.h
Labels: ready-for-testing

#262 Simplify the replication of expression by clone function
  src/parser/Clauses.h
  src/parser/parser.yy
  src/util/ExpressionUtils.h
  src/validator/GoValidator.cpp
  src/validator/MutateValidator.cpp
  src/validator/TraversalValidator.cpp
  src/visitor/RewriteLabelAttrVisitor.cpp
Labels: ready-for-testing

#260 Fix failure when all field are constant expressions in yield sentence with filter
  src/executor/query/FilterExecutor.cpp
  src/validator/YieldValidator.cpp
  src/validator/YieldValidator.h
  tests/query/v1/test_yield.py
Labels: ready-for-testing

#263 Bound value for index
  src/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/optimizer/CMakeLists.txt
  src/optimizer/OptimizerUtils.cpp
  src/optimizer/OptimizerUtils.h
  src/optimizer/test/CMakeLists.txt
  src/optimizer/test/IndexBoundValueTest.cpp
Labels: ready-for-testing

#270 Refactor executor make function
  src/executor/Executor.cpp
  src/executor/Executor.h
  src/executor/logic/LoopExecutor.cpp
  src/executor/logic/LoopExecutor.h
  src/executor/logic/SelectExecutor.cpp
  src/executor/logic/SelectExecutor.h
  src/executor/test/LogicExecutorsTest.cpp
  src/planner/Logic.h
Labels: ready-for-testing

#247 Add optimizer
  ci/test.sh
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  resources/gflags.json
  src/context/QueryContext.h
  src/daemons/CMakeLists.txt
  src/mock/test/CMakeLists.txt
  src/optimizer/CMakeLists.txt
  src/optimizer/OptGroup.cpp
  src/optimizer/OptGroup.h
  src/optimizer/OptRule.cpp
  src/optimizer/OptRule.h
  src/optimizer/Optimizer.cpp
  src/optimizer/Optimizer.h
  src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
  src/optimizer/rule/PushFilterDownGetNbrsRule.h
  src/planner/ExecutionPlan.cpp
  src/planner/ExecutionPlan.h
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/planner/Query.cpp
  src/service/GraphFlags.cpp
  src/service/GraphFlags.h
  src/service/QueryInstance.cpp
  src/service/QueryInstance.h
  src/visitor/CMakeLists.txt
  src/visitor/ExtractFilterExprVisitor.cpp
  src/visitor/ExtractFilterExprVisitor.h
  tests/admin/test_configs.py
  tests/common/global_data_loader.py
  tests/common/nebula_service.py
  tests/common/nebula_test_suite.py
  tests/nebula-test-run.py
  tests/ntr.out-of-source
  tests/query/v2/test_optimizer.py
Labels: ready-for-testing

#273 change null value to empty value
  src/context/Iterator.cpp
  src/context/test/IteratorTest.cpp
  tests/mutate/test_delete_vertices.py
  tests/query/v1/test_fetch_vertex.py
  tests/query/v1/test_go.py
  tests/query/v2/test_get_subgraph.py
Labels: ready-for-testing

#274 Fix execute single test failed
  tests/nebula-test-run.py
Labels: ready-for-testing

#267 Add input vars and output vars.
  src/executor/Executor.cpp
  src/executor/query/DataJoinExecutor.cpp
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/ProjectExecutor.cpp
  src/executor/test/AggregateTest.cpp
  src/executor/test/DataCollectTest.cpp
  src/executor/test/DataJoinTest.cpp
  src/executor/test/DedupTest.cpp
  src/executor/test/FilterTest.cpp
  src/executor/test/LimitTest.cpp
  src/executor/test/LogicExecutorsTest.cpp
  src/executor/test/ProjectTest.cpp
  src/executor/test/SetExecutorTest.cpp
  src/executor/test/SortTest.cpp
  src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/planner/Query.cpp
  src/planner/Query.h
  src/scheduler/Scheduler.cpp
  src/service/QueryInstance.cpp
  src/validator/ExpressionProps.cpp
  src/validator/ExpressionProps.h
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchVerticesValidator.cpp
  src/validator/GetSubgraphValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/MutateValidator.cpp
  src/validator/PipeValidator.cpp
  src/validator/SequentialValidator.cpp
  src/validator/SetValidator.cpp
  src/validator/TraversalValidator.cpp
  src/validator/Validator.cpp
  src/validator/YieldValidator.cpp
  src/validator/test/FetchEdgesTest.cpp
  src/validator/test/FetchVerticesTest.cpp
  src/validator/test/ValidatorTestBase.cpp
Labels: ready-for-testing

#266 add prop iterator
  src/context/Iterator.cpp
  src/context/Iterator.h
  src/context/Result.h
  src/context/test/IteratorTest.cpp
  src/executor/query/GetPropExecutor.h
Labels: ready-for-testing

#282 Subgraph zero step
  src/context/test/IteratorTest.cpp
  src/validator/GetSubgraphValidator.cpp
  src/validator/GetSubgraphValidator.h
  src/validator/test/GetSubgraphValidatorTest.cpp
  tests/query/v2/test_get_subgraph.py
Labels: ready-for-testing

#278 fix bug in PushFilterDownGetNbrsRule
  src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
Labels: ready-for-testing

#233 Support integer vid.
  src/context/Iterator.cpp
  src/context/ValidateContext.h
  src/executor/admin/SpaceExecutor.cpp
  src/executor/admin/SwitchSpaceExecutor.cpp
  src/executor/maintain/EdgeExecutor.cpp
  src/executor/maintain/TagExecutor.cpp
  src/executor/mutate/DeleteExecutor.cpp
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetVerticesExecutor.cpp
  src/executor/test/GetNeighborsTest.cpp
  src/mock/StorageCache.cpp
  src/mock/StorageCache.h
  src/mock/test/SchemaTest.cpp
  src/mock/test/TestMock.cpp
  src/optimizer/OptimizerUtils.cpp
  src/optimizer/test/IndexBoundValueTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/ColumnTypeDef.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/planner/Admin.cpp
  src/planner/Admin.h
  src/service/PermissionManager.cpp
  src/service/QueryInstance.cpp
  src/service/Session.h
  src/service/test/CMakeLists.txt
  src/util/SchemaUtil.cpp
  src/util/SchemaUtil.h
  src/util/ToJson.cpp
  src/util/ToJson.h
  src/validator/AdminValidator.cpp
  src/validator/AdminValidator.h
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchVerticesValidator.cpp
  src/validator/TraversalValidator.cpp
  src/validator/UseValidator.cpp
  src/validator/Validator.cpp
  src/validator/Validator.h
  src/validator/test/GetSubgraphValidatorTest.cpp
  src/validator/test/ValidatorTestBase.h
  tests/admin/test_space.py
  tests/common/global_data_loader.py
  tests/common/nebula_test_suite.py
  tests/maintain/test_tag_edge.py
  tests/mutate/test_insert_1.py
  tests/mutate/test_insert_2.py
  tests/mutate/test_update_upsert.py
  tests/mutate/test_update_upsert_2.py
Labels: ready-for-testing

#281 Validator of IndexScan.
  src/validator/CMakeLists.txt
  src/validator/IndexScanValidator.cpp
  src/validator/IndexScanValidator.h
Labels: ready-for-testing

#289 Remove offline flag when rebuild index
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
Labels: documentation, ready-for-testing

#284 Fix get edge.
  src/context/Iterator.cpp
  src/context/Iterator.h
  src/context/test/IteratorTest.cpp
  tests/common/nebula_test_suite.py
  tests/nebula-test-run.py
Labels: ready-for-testing

#288 Add constant expression folding visitor
  .gitignore
  src/context/test/CMakeLists.txt
  src/optimizer/OptimizerUtils.cpp
  src/parser/test/CMakeLists.txt
  src/util/CMakeLists.txt
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/validator/YieldValidator.cpp
  src/validator/YieldValidator.h
  src/visitor/CMakeLists.txt
  src/visitor/FoldConstantExprVisitor.cpp
  src/visitor/FoldConstantExprVisitor.h
  src/visitor/test/CMakeLists.txt
  src/visitor/test/FoldConstantExprVisitorTest.cpp
Labels: ready-for-testing

#287 Correct/remove timezone
  src/optimizer/OptimizerUtils.cpp
  tests/common/nebula_test_suite.py
Labels: ready-for-testing

#257 Added CREATE INDEX
  src/context/QueryContext.cpp
  src/context/QueryContext.h
  src/context/ValidateContext.h
  src/executor/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/maintain/EdgeExecutor.cpp
  src/executor/maintain/EdgeExecutor.h
  src/executor/maintain/EdgeIndexExecutor.cpp
  src/executor/maintain/EdgeIndexExecutor.h
  src/executor/maintain/TagExecutor.cpp
  src/executor/maintain/TagExecutor.h
  src/executor/maintain/TagIndexExecutor.cpp
  src/executor/maintain/TagIndexExecutor.h
  src/parser/ColumnTypeDef.h
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/planner/Maintain.cpp
  src/planner/Maintain.h
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/service/PermissionCheck.cpp
  src/service/QueryEngine.cpp
  src/service/QueryEngine.h
  src/util/CMakeLists.txt
  src/util/IndexUtil.cpp
  src/util/IndexUtil.h
  src/util/SchemaUtil.cpp
  src/validator/MaintainValidator.cpp
  src/validator/MaintainValidator.h
  src/validator/Validator.cpp
Labels: in progress, ready-for-testing

#292 Fix column def
  src/mock/MetaCache.cpp
  src/mock/test/TestMock.cpp
  src/optimizer/OptimizerUtils.cpp
  src/optimizer/test/IndexBoundValueTest.cpp
  src/util/SchemaUtil.cpp
  src/util/ToJson.cpp
  src/validator/MaintainValidator.cpp
Labels: ready-for-testing

#294 Update vid type definition in SpaceDesc
  src/executor/admin/SpaceExecutor.cpp
  src/mock/MetaCache.cpp
  src/mock/test/TestMock.cpp
  src/util/SchemaUtil.cpp
  src/util/SchemaUtil.h
  src/util/ToJson.cpp
  src/validator/AdminValidator.cpp
  src/validator/MutateValidator.cpp
  src/validator/TraversalValidator.cpp
  tests/admin/test_configs.py
Labels: ready-for-testing

#296 fixed bug for create tag|edge index
  src/planner/Maintain.h
  src/validator/MaintainValidator.cpp
  src/validator/Validator.cpp
Labels: ready-for-testing

#291 Make static empty result initialize lazily
  src/context/ExecutionContext.cpp
  src/context/Result.cpp
  src/context/Result.h
Labels: ready-for-testing

#264 Support the yield clause when fetch vertices on *.
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/validator/ExpressionProps.cpp
  src/validator/ExpressionProps.h
  src/validator/FetchVerticesValidator.cpp
  src/validator/FetchVerticesValidator.h
  src/validator/test/FetchVerticesTest.cpp
  src/validator/test/ValidatorTestBase.cpp
  src/validator/test/YieldValidatorTest.cpp
  src/visitor/DeducePropsVisitor.cpp
  tests/query/v1/test_fetch_vertex.py
  tests/query/v2/test_label_expr.py
Labels: ready-for-testing

#293 Remove unused ColumnTypeDef defined in graph
  src/executor/admin/PartExecutor.cpp
  src/executor/admin/SpaceExecutor.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/ColumnTypeDef.h
  src/parser/parser.yy
  src/util/SchemaUtil.cpp
  src/util/SchemaUtil.h
  src/util/ToJson.cpp
  src/validator/AdminValidator.cpp
  src/validator/MaintainValidator.cpp
Labels: ready-for-testing

#272 Optimizer rule for index scan
  src/optimizer/CMakeLists.txt
  src/optimizer/rule/IndexScanRule.cpp
  src/optimizer/rule/IndexScanRule.h
  src/optimizer/test/CMakeLists.txt
  src/optimizer/test/IndexScanRuleTest.cpp
  src/planner/Query.h
  src/validator/IndexScanValidator.cpp
  src/validator/IndexScanValidator.h
  src/validator/Validator.cpp
Labels: ready-for-testing

#290 Add extractExprProp & RewriteInputProp visitor & IN NOT IN test case
  src/validator/GoValidator.cpp
  src/visitor/CMakeLists.txt
  src/visitor/ExtractFilterExprVisitor.h
  src/visitor/ExtractPropExprVisitor.cpp
  src/visitor/ExtractPropExprVisitor.h
  src/visitor/RewriteInputPropVisitor.cpp
  src/visitor/RewriteInputPropVisitor.h
  tests/query/v2/test_in_not_in.py
Labels: ready-for-testing
