Repository vesoft-inc/nebula-graph, pull requests merged in 2021-04, with the labels that each got.

#910 [Simple] Clean *.lock files in Makefile
  tests/Makefile
Labels: ready-for-review, ready-for-testing

#913 Add the lack header.
  src/planner/ExecutionPlan.h
Labels: ready-for-review, ready-for-testing

#911 Cleanup cluster workflow and disable centos6 test environment
  .github/workflows/cluster.yml
  .github/workflows/package.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  ci/nebula-test-job.yml
  ci/test-k8s-cluster.sh
  ci/test.sh
  ci/tests.txt
  tests/query/stateless/test_range.py
  tests/tck/features/insert/BoundCheck.feature
Labels: ready-for-testing

#850 Support comparison of nested operator infos in TCK frame
  tests/README.md
  tests/common/plan_differ.py
  tests/tck/features/optimizer/MergeGetNbrsDedupProjectRule.feature
  tests/tck/features/optimizer/MergeGetVerticesDedupProjectRule.feature
  tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
  tests/tck/features/optimizer/PushLimitDownRule.feature
  tests/tck/features/optimizer/TopNRule.feature
Labels: doc required, ready-for-review, ready-for-testing

#917 Fix delete vertex check wrong vid type
  src/validator/MutateValidator.cpp
  tests/tck/features/delete/DeleteEdge.IntVid.feature
  tests/tck/features/delete/DeleteEdge.feature
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/delete/DeleteVertex.feature
Labels: ready-for-testing

#916 Fix docker build script
  package/package.sh
Labels: ready-for-testing

#837 Refactor plan node dependencies usage
  src/executor/Executor.cpp
  src/optimizer/OptGroup.cpp
  src/optimizer/Optimizer.cpp
  src/optimizer/Optimizer.h
  src/planner/ExecutionPlan.cpp
  src/planner/ExecutionPlan.h
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/validator/Validator.cpp
  src/validator/test/ValidatorTestBase.cpp
Labels: ready-for-testing

#912 remove redundant project&dedup in findpath & fix path error
  .gitignore
  src/executor/algo/ConjunctPathExecutor.cpp
  src/executor/algo/ConjunctPathExecutor.h
  src/validator/FindPathValidator.cpp
  src/validator/FindPathValidator.h
  src/validator/test/FindPathValidatorTest.cpp
  tests/tck/features/path/ShortestPath.IntVid.feature
  tests/tck/features/path/ShortestPath.feature
Labels: bug, ready-for-review, ready-for-testing

#803 Rewrite unaryNot EXPR
  src/context/ast/QueryAstContext.h
  src/planner/match/PropIndexSeek.cpp
  src/planner/match/WhereClausePlanner.cpp
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/validator/MatchValidator.cpp
  src/visitor/CMakeLists.txt
  src/visitor/RewriteUnaryNotExprVisitor.cpp
  src/visitor/RewriteUnaryNotExprVisitor.h
  src/visitor/test/CMakeLists.txt
  src/visitor/test/FoldConstantExprVisitorTest.cpp
  src/visitor/test/RewriteUnaryNotExprVisitorTest.cpp
  src/visitor/test/VisitorTestBase.h
  tests/tck/features/expression/UnaryExpr.feature
Labels: depend on common, ready-for-review, ready-for-testing

#842 add optimizer rule for having clause
  src/optimizer/CMakeLists.txt
  src/optimizer/rule/PushFilterDownAggregateRule.cpp
  src/optimizer/rule/PushFilterDownAggregateRule.h
  src/planner/Query.cpp
  src/planner/Query.h
  tests/tck/features/optimizer/PushFilterDownAggregateRule.feature
Labels: ready-for-review, ready-for-testing

#921 Checkout special branch of commom and storage repos
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#918 [Cherrypick] #917 #912
  .gitignore
  src/executor/algo/ConjunctPathExecutor.cpp
  src/executor/algo/ConjunctPathExecutor.h
  src/validator/FindPathValidator.cpp
  src/validator/FindPathValidator.h
  src/validator/MutateValidator.cpp
  src/validator/test/FindPathValidatorTest.cpp
  tests/tck/features/delete/DeleteEdge.IntVid.feature
  tests/tck/features/delete/DeleteEdge.feature
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/delete/DeleteVertex.feature
  tests/tck/features/path/ShortestPath.IntVid.feature
  tests/tck/features/path/ShortestPath.feature
Labels: ready-for-testing

#809 add isEmpty
  src/parser/parser.yy
  src/parser/scanner.lex
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/ExtractPropExprVisitor.cpp
  tests/tck/features/go/GO.feature
Labels: depend on common, doc required, ready-for-review, ready-for-testing

#919 fix match agg check
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  tests/tck/features/aggregate/Agg.feature
Labels: ready-for-review, ready-for-testing

#901 fix agg executor
  src/executor/query/AggregateExecutor.cpp
  src/executor/test/AggregateTest.cpp
  tests/tck/features/aggregate/Agg.feature
Labels: depend on common, ready-for-review, ready-for-testing

#922 fix cluster getNeightborIter
  src/context/Iterator.cpp
  src/context/test/IteratorTest.cpp
Labels: bug, ready-for-review, ready-for-testing

#920 Checkout special branch of commom and storage repos
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#932 Fix seek by negative vid
  src/validator/MatchValidator.cpp
  src/visitor/FoldConstantExprVisitor.cpp
  tests/tck/features/match/SeekById.intVid.feature
Labels: bug, ready-for-review, ready-for-testing

#924 Do not build docker image for release branch when committing
  .github/workflows/docker.yml
  .github/workflows/nightly.yml
Labels: ready-for-testing

#933 check type of index
  tests/tck/features/index/TagEdgeIndex.feature
Labels: depend on storage, ready-for-review, ready-for-testing

#931 Cherrypick #901 #919 #922 #932 #849
  .github/workflows/package.yml
  .github/workflows/pull_request.yml
  src/context/Iterator.cpp
  src/context/test/IteratorTest.cpp
  src/executor/query/AggregateExecutor.cpp
  src/executor/test/AggregateTest.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/validator/MatchValidator.cpp
  src/visitor/FoldConstantExprVisitor.cpp
  tests/Makefile
  tests/common/comparator.py
  tests/common/types.py
  tests/common/utils.py
  tests/tck/conftest.py
  tests/tck/features/agg/Agg.feature
  tests/tck/features/bugfix/MatchReturnEmptyTag.feature
  tests/tck/features/delete/DeleteEdge.IntVid.feature
  tests/tck/features/delete/DeleteEdge.feature
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/fetch/FetchEmpty.feature
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/index/Index.feature
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/LookUp.IntVid.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/match/SeekById.intVid.feature
  tests/tck/features/mutate/InsertWithTimeType.feature
  tests/tck/features/parser/Example.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/ttl/TTL.feature
  tests/tck/features/update/Update.IntVid.feature
  tests/tck/features/update/Update.feature
  tests/tck/features/user/User.feature
Labels: ready-for-testing

#769 Fix filter string with null
  src/optimizer/OptimizerUtils.cpp
  tests/tck/features/match/Base.feature
Labels: ready-for-review, ready-for-testing

#936 cherrypick #933 #904
  package/package.sh
  tests/maintain/test_index.py
  tests/maintain/test_zone.py
  tests/nebula-test-run.py
  tests/query/stateless/test_lookup.py
  tests/query/stateless/test_range.py
  tests/tck/conftest.py
  tests/tck/features/index/TagEdgeIndex.feature
  tests/tck/features/lookup/LookUp.feature
Labels: ready-for-testing

#876 improved testcases for index ttl
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/index/Index.feature
Labels: doc required, ready-for-review, ready-for-testing

#938 implement PlanNode clone interface
  src/optimizer/rule/IndexScanRule.cpp
  src/optimizer/rule/LimitPushDownRule.cpp
  src/optimizer/rule/MergeGetNbrsAndDedupRule.cpp
  src/optimizer/rule/MergeGetNbrsAndProjectRule.cpp
  src/optimizer/rule/MergeGetVerticesAndDedupRule.cpp
  src/optimizer/rule/MergeGetVerticesAndProjectRule.cpp
  src/optimizer/rule/PushFilterDownAggregateRule.cpp
  src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
  src/planner/Logic.cpp
  src/planner/Logic.h
  src/planner/PlanNode.h
  src/planner/Query.cpp
  src/planner/Query.h
Labels: ready-for-review, ready-for-testing

#945 Solve the unstable case for meanless order by.
  tests/tck/features/go/GO.IntVid.feature
Labels: ready-for-testing

#950 [cherrypick] #855 #893 #896 #904 #916 #911 #924
  .dockerignore
  .github/workflows/cluster.yml
  .github/workflows/docker.yml
  .github/workflows/nightly.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitignore
  Dockerfile
  ci/nebula-test-job.yml
  ci/test-k8s-cluster.sh
  ci/test.sh
  ci/tests.txt
  package/CMakeLists.txt
  package/package.sh
  tests/README.md
  tests/query/stateless/test_range.py
  tests/tck/features/index/TagEdgeIndex.feature
  tests/tck/features/insert/BoundCheck.feature
  tests/tck/features/mutate/InsertWithTimeType.feature
Labels: ready-for-testing

#951 Update package.sh
  package/package.sh
Labels: ready-for-testing

#953 Cherrypick #874
  .github/actions/upload-assets-action/README.md
  .github/actions/upload-assets-action/action.yml
  .github/actions/upload-to-oss-action/README.md
  .github/actions/upload-to-oss-action/action.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#926 fix case sensitivity of function name
  src/parser/parser.yy
  src/util/ExpressionUtils.cpp
  src/validator/GroupByValidator.cpp
  src/validator/GroupByValidator.h
  src/validator/test/GroupByValidatorTest.cpp
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/bugfix/MatchUsedInPipe.feature
  tests/tck/features/yield/yield.feature
Labels: depend on common, doc required, ready-for-review, ready-for-testing

#943 fix date() crash
  src/parser/parser.yy
  tests/tck/features/expression/FunctionCall.feature
Labels: bug, ready-for-testing

#929 Insert if not exist
  src/executor/mutate/InsertExecutor.cpp
  src/parser/MaintainSentences.cpp
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/planner/Mutate.cpp
  src/planner/Mutate.h
  src/validator/MutateValidator.cpp
  src/validator/MutateValidator.h
  tests/tck/features/insert/InsertIfNotExists.feature
Labels: doc required, ready-for-review, ready-for-testing

#957 Returns all latest version of edges schema
  src/validator/test/MockSchemaManager.h
Labels: ready-for-review, ready-for-testing

#955 small fix
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchVerticesValidator.cpp
  src/validator/GoValidator.cpp
Labels: ready-for-review, ready-for-testing

#958 fix predicate expression with agg
  src/util/ExpressionUtils.h
  tests/tck/features/expression/Predicate.feature
Labels: ready-for-review, ready-for-testing

#960 add tck case
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/expression/Reduce.feature
Labels: ready-for-review, ready-for-testing

#967 Fix the extra copy warning and float abs warning.
  src/planner/Query.cpp
  src/validator/LookupValidator.cpp
Labels: ready-for-testing

#964 change error informations
  tests/admin/test_parts.py
  tests/tck/features/schema/Schema.feature
Labels: ready-for-review, ready-for-testing

#962 add description for storage error code E_DATA_CONFLICT_ERROR
  src/executor/StorageAccessExecutor.h
Labels: ready-for-review, ready-for-testing

#947 refactor find visitors
  src/util/ExpressionUtils.h
  src/validator/GroupByValidator.cpp
  src/visitor/CMakeLists.txt
  src/visitor/CollectAllExprsVisitor.cpp
  src/visitor/CollectAllExprsVisitor.h
  src/visitor/FindAnyExprVisitor.cpp
  src/visitor/FindAnySubExprVisitor.cpp
  src/visitor/FindAnySubExprVisitor.h
  src/visitor/FindVisitor.h
  src/visitor/FindVisitor.inl
Labels: ready-for-review, ready-for-testing

#963 Fix float precision in comparison
  src/optimizer/OptimizerUtils.h
  src/optimizer/test/IndexBoundValueTest.cpp
  src/optimizer/test/IndexScanRuleTest.cpp
  tests/tck/features/lookup/LookUp.IntVid.feature
  tests/tck/features/lookup/LookUp.feature
Labels: ready-for-review, ready-for-testing

#972 fix filter executor
  src/executor/query/FilterExecutor.cpp
Labels: depend on common, ready-for-review, ready-for-testing

#974 Fix package error when cmake's version less than 3.13
  package/package.sh
Labels: ready-for-testing

#632 Match seek by edge.
  src/context/ast/QueryAstContext.h
  src/planner/match/LabelIndexSeek.cpp
  src/planner/match/LabelIndexSeek.h
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/MatchSolver.cpp
  src/planner/match/MatchSolver.h
  src/planner/match/PropIndexSeek.cpp
  src/validator/MatchValidator.cpp
  src/validator/test/MatchValidatorTest.cpp
  src/validator/test/MockIndexManager.cpp
  src/validator/test/MockIndexManager.h
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/SeekByEdge.feature
Labels: doc required, ready-for-review, ready-for-testing

#952 Add storage_client_timeout_ms and ws_meta_http_port into conf file
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
Labels: ready-for-testing

#862 delete unnecessary project node
  src/optimizer/CMakeLists.txt
  src/optimizer/OptGroup.h
  src/optimizer/rule/RemoveNoopProjectRule.cpp
  src/optimizer/rule/RemoveNoopProjectRule.h
  tests/tck/features/optimizer/PushFilterDownAggregateRule.feature
  tests/tck/features/optimizer/RemoveUselessProjectRule.feature
Labels: ready-for-review, ready-for-testing

#975 enhance FindVisitor
  src/validator/test/YieldValidatorTest.cpp
  src/visitor/FindVisitor.inl
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: depend on common, ready-for-review, ready-for-testing

#978 Optimize match expression construction
  src/optimizer/rule/IndexScanRule.cpp
  src/planner/match/MatchSolver.cpp
Labels: ready-for-testing

#973 [opencypher compatibility] Support using exists with dynamic map
  src/parser/parser.yy
  tests/tck/features/expression/Predicate.feature
Labels: bug, depend on common, ready-for-testing

#971 Insert with default propNames
  src/parser/MutateSentences.h
  src/parser/parser.yy
  src/validator/MutateValidator.cpp
  tests/tck/features/insert/InsertIfNotExists.feature
Labels: ready-for-testing

#988 Refactor unaryNotExprRewriter
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/validator/MatchValidator.cpp
  src/visitor/CMakeLists.txt
  src/visitor/RewriteUnaryNotExprVisitor.cpp
  src/visitor/RewriteUnaryNotExprVisitor.h
  src/visitor/test/RewriteUnaryNotExprVisitorTest.cpp
Labels: ready-for-testing

#990 make findvisitor suitable for more scenarios
  src/util/ExpressionUtils.h
  src/validator/GroupByValidator.cpp
  src/visitor/CMakeLists.txt
  src/visitor/FindVisitor.cpp
  src/visitor/FindVisitor.h
Labels: ready-for-testing

#994 Add the issue pr template.
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/bugfix.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: ready-for-testing

#993 fix insert ci sometimes fail
  tests/tck/features/insert/InsertIfNotExists.feature
Labels: ready-for-testing

#987 Reorg the configuration file.
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
Labels: ready-for-testing
