Repository vesoft-inc/nebula-graph, pull requests merged in 2021-02, with the labels that each got.

#691 Ignore merged PR in github action
  .github/workflows/pull_request.yml
Labels: ready-for-testing

#680 show create space support atomic_edge field
  src/executor/admin/SpaceExecutor.cpp
  tests/admin/test_space.py
Labels: in progress, ready-for-testing

#681 fix unwind agg
  tests/tck/features/match/WithUnwind.feature
Labels: in progress, ready-for-testing

#556 Add flag to determine whether partial success results are valid
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  resources/gflags.json
  src/executor/StorageAccessExecutor.h
  src/executor/mutate/DeleteExecutor.cpp
  src/executor/mutate/InsertExecutor.cpp
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetPropExecutor.h
  src/executor/query/IndexScanExecutor.cpp
  src/service/GraphFlags.cpp
  src/service/GraphFlags.h
  src/service/QueryInstance.cpp
  tests/admin/test_configs.py
Labels: ready-for-review, ready-for-testing

#608 add a test case for predicate, list comprehension and reduce
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/expression/predicate.feature
  tests/tck/features/expression/reduce.feature
Labels: ready-for-testing

#714 Print errorcode's name
  src/executor/StorageAccessExecutor.h
Labels: ready-for-testing

#660 add Subgraph executor & refactor subgraph
  src/executor/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/algo/SubgraphExecutor.cpp
  src/executor/algo/SubgraphExecutor.h
  src/executor/query/DataCollectExecutor.cpp
  src/executor/test/DataCollectTest.cpp
  src/planner/Algo.h
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/validator/GetSubgraphValidator.cpp
  src/validator/GetSubgraphValidator.h
  src/validator/TraversalValidator.cpp
  src/validator/TraversalValidator.h
  src/validator/test/GetSubgraphValidatorTest.cpp
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing

#734 fix rewrite predicate expression bug
  src/visitor/RewriteMatchLabelVisitor.cpp
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/expression/predicate.feature
  tests/tck/features/expression/reduce.feature
Labels: ready-for-testing

#715 Add test case for rc1 bug
  tests/pytest.ini
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
Labels: bug, ready-for-testing

#686 Add several counters
  .gitignore
  src/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/daemons/GraphDaemon.cpp
  src/service/GraphService.cpp
  src/service/QueryInstance.cpp
  src/stats/CMakeLists.txt
  src/stats/StatsDef.cpp
  src/stats/StatsDef.h
Labels: ready-for-testing

#733 migrate some expression test cases to tck
  tests/query/v2/test_case_expression.py
  tests/query/v2/test_in_not_in.py
  tests/query/v2/test_regex_match.py
  tests/tck/features/expression/Case.feature
  tests/tck/features/expression/In.feature
  tests/tck/features/expression/NotIn.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/expression/Reduce.feature
  tests/tck/features/expression/Regex.feature
Labels: ready-for-testing

#737 Fix binary input plan node explain string about input variables
  src/planner/PlanNode.cpp
Labels: ready-for-testing

#730 add opencypher
  tests/Makefile
  tests/pytest.ini
  tests/tck/openCypher/features/expressions/map/Map1.feature
  tests/tck/openCypher/features/expressions/map/Map2.feature
  tests/tck/openCypher/features/expressions/path/Path1.feature
  tests/tck/openCypher/features/expressions/path/Path2.feature
  tests/tck/openCypher/features/expressions/path/Path3.feature
  tests/tck/steps/test_tck.py
Labels: ready-for-testing

#736 add ascending/descending
  .linters/cpp/checkKeyword.py
  src/parser/parser.yy
  src/parser/scanner.lex
  tests/tck/features/match/MatchById.IntVid.feature
Labels: ready-for-review, ready-for-testing

#739 Remove the unused input for some plan nodes.
  src/planner/Admin.cpp
  src/planner/Admin.h
  src/planner/Mutate.cpp
  src/planner/Mutate.h
Labels: ready-for-testing

#735 Use absolute path for nebula binary and config file in docker image
  Dockerfile
Labels: ready-for-testing

#741 add Scientific notation of float
  src/parser/scanner.lex
  tests/tck/features/yield/yield.feature
Labels: doc required, ready-for-review, ready-for-testing

#742 [Bugfix] Label expression in with clause has default alias: its label name
  src/validator/MatchValidator.cpp
  tests/tck/features/match/WithUnwind.feature
Labels: ready-for-testing

#743 Improve variable-length match plan with Loop planNode
  src/context/ExecutionContext.h
  src/context/Iterator.h
  src/executor/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/query/UnionAllVersionVarExecutor.cpp
  src/executor/query/UnionAllVersionVarExecutor.h
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/planner/Query.h
  src/planner/SequentialPlanner.cpp
  src/planner/match/Expand.cpp
  src/planner/match/Expand.h
  src/planner/match/MatchSolver.cpp
  src/scheduler/Scheduler.cpp
  src/scheduler/Scheduler.h
  src/validator/test/MatchValidatorTest.cpp
  src/validator/test/QueryValidatorTest.cpp
  tests/tck/features/match/Base.feature
Labels: ready-for-review, ready-for-testing

#745 Move the constructor of Sequential Iterator to source file
  src/context/Iterator.cpp
  src/context/Iterator.h
Labels: ready-for-testing

#740 support function sign in parser
  src/parser/parser.yy
  tests/tck/features/expression/FunctionCall.feature
Labels: doc required, ready-for-testing

#770 Correct the new error msg.
  tests/tck/features/update/Update.IntVid.feature
  tests/tck/features/update/Update.feature
Labels: ready-for-review, ready-for-testing

#757 Improve iters.
  src/context/CMakeLists.txt
  src/context/Iterator.cpp
  src/context/Iterator.h
  src/context/test/IteratorTest.cpp
  src/executor/mutate/DeleteExecutor.cpp
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/test/LimitTest.cpp
  src/validator/GoValidator.cpp
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing

#727 update storage tool to package
  package/CMakeLists.txt
Labels: ready-for-review, ready-for-testing

#759 Fix download core problem
  src/parser/MutateSentences.h
  src/validator/DownloadValidator.cpp
Labels: ready-for-review, ready-for-testing

#775 Fix download mem leak.
  src/parser/MutateSentences.h
  src/parser/parser.yy
Labels: ready-for-testing
