Repository vesoft-inc/nebula-graph, pull requests merged in 2021-06, with the labels that each got.

#1099 Modify the onFinish and onError to private in QueryInstance.
  src/service/QueryInstance.h
Labels: ready-for-testing

#1081 A bright new scheduler implementation based on BFS and Promise/Future mode.
  src/scheduler/AsyncMsgNotifyBasedScheduler.cpp
  src/scheduler/AsyncMsgNotifyBasedScheduler.h
  src/scheduler/CMakeLists.txt
  src/scheduler/Scheduler.cpp
  src/scheduler/Scheduler.h
  src/service/QueryInstance.cpp
Labels: hi-pri, ready-for-testing

#1100 Increase timeout to 180000.
  tests/common/utils.py
Labels: ready-for-testing, wip

#1101 check ptr before use
  src/executor/query/GetNeighborsExecutor.cpp
Labels: ready-for-testing

#1097 Set local_config default value to true
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  tests/common/nebula_service.py
Labels: doc affected, ready-for-testing

#280 Support sessions saving by metad
  resources/gflags.json
  src/CMakeLists.txt
  src/context/ValidateContext.h
  src/daemons/GraphDaemon.cpp
  src/executor/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/StorageAccessExecutor.h
  src/executor/admin/SessionExecutor.cpp
  src/executor/admin/SessionExecutor.h
  src/executor/test/GetNeighborsTest.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/MaintainSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  src/planner/plan/Admin.h
  src/planner/plan/PlanNode.cpp
  src/planner/plan/PlanNode.h
  src/service/CMakeLists.txt
  src/service/GraphFlags.cpp
  src/service/GraphFlags.h
  src/service/GraphService.cpp
  src/service/GraphService.h
  src/service/PermissionCheck.cpp
  src/service/PermissionCheck.h
  src/service/PermissionManager.cpp
  src/service/PermissionManager.h
  src/service/QueryEngine.cpp
  src/service/QueryEngine.h
  src/service/RequestContext.h
  src/service/Session.cpp
  src/service/Session.h
  src/service/SessionManager.cpp
  src/service/SessionManager.h
  src/service/test/CMakeLists.txt
  src/service/test/SessionManagerTest.cpp
  src/session/CMakeLists.txt
  src/session/ClientSession.cpp
  src/session/ClientSession.h
  src/session/SessionManager.cpp
  src/session/SessionManager.h
  src/validator/AdminValidator.cpp
  src/validator/AdminValidator.h
  src/validator/UseValidator.cpp
  src/validator/Validator.cpp
  src/validator/test/AdminValidatorTest.cpp
  src/validator/test/ValidatorTestBase.h
  tests/Makefile
  tests/admin/test_configs.py
  tests/common/nebula_service.py
  tests/job/__init__.py
  tests/job/test_session.py
  tests/nebula-test-run.py
Labels: ready-for-testing

#1105 Catch the exception in each future callback.
  src/scheduler/AsyncMsgNotifyBasedScheduler.cpp
Labels: ready-for-testing

#1106 fix insert vertex with default prop names bug
  src/validator/MutateValidator.cpp
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
Labels: ready-for-testing

#1075 Add TCK cases about NULL comparison and NULL with math functions
  tests/tck/features/expression/Null.feature
Labels: ready-for-testing

#1043 Check Integer overflow in expression calculation
  src/parser/GraphScanner.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/validator/GoValidator.cpp
  src/validator/LookupValidator.cpp
  src/validator/MaintainValidator.cpp
  src/validator/MatchValidator.cpp
  src/validator/YieldValidator.cpp
  src/visitor/FoldConstantExprVisitor.cpp
  src/visitor/FoldConstantExprVisitor.h
  src/visitor/test/FilterTransformTest.cpp
  tests/tck/features/go/GO.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: bug, depend on common, ready-for-testing

#1091 add path filter
  src/context/Iterator.cpp
  src/context/Iterator.h
  src/context/ast/QueryAstContext.h
  src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
  src/parser/TraverseSentences.cpp
  src/parser/parser.yy
  src/planner/ngql/PathPlanner.cpp
  src/validator/FindPathValidator.cpp
  src/validator/FindPathValidator.h
  src/validator/test/FindPathValidatorTest.cpp
  tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
  tests/tck/features/path/AllPath.IntVid.feature
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/NoLoop.IntVid.feature
  tests/tck/features/path/NoLoop.feature
  tests/tck/features/path/ShortestPath.IntVid.feature
  tests/tck/features/path/ShortestPath.feature
Labels: doc affected, ready-for-testing

#1131 fixed all broken links
  CONTRIBUTING.md
  README-CN.md
  README.md
Labels: ready-for-testing

#1134 get subgraph no prop
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/validator/FindPathValidator.cpp
  src/validator/GetSubgraphValidator.cpp
  src/validator/GetSubgraphValidator.h
  src/validator/test/GetSubgraphValidatorTest.cpp
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: doc affected, incompatible, ready-for-testing

#1112 Add test for do execute after signout and fix the return errormsg
  src/service/GraphService.cpp
  tests/job/test_session.py
Labels: ready-for-testing

#1135 add listener conf file for make install
  package/CMakeLists.txt
Labels: ready-for-testing

#1098 Initialize column names for some plan node according to their dependencies
  src/parser/Clauses.h
  src/planner/match/YieldClausePlanner.cpp
  src/planner/ngql/PathPlanner.cpp
  src/planner/plan/PlanNode.cpp
  src/planner/plan/PlanNode.h
  src/planner/plan/Query.cpp
  src/planner/plan/Query.h
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchEdgesValidator.h
  src/validator/FetchVerticesValidator.cpp
  src/validator/FetchVerticesValidator.h
  src/validator/GetSubgraphValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/GoValidator.h
  src/validator/GroupByValidator.cpp
  src/validator/GroupByValidator.h
  src/validator/LookupValidator.cpp
  src/validator/LookupValidator.h
  src/validator/MatchValidator.cpp
  src/validator/MutateValidator.cpp
  src/validator/SetValidator.cpp
  src/validator/TraversalValidator.cpp
  src/validator/Validator.cpp
  src/validator/Validator.h
  src/validator/YieldValidator.cpp
  src/validator/YieldValidator.h
Labels: ready-for-testing

#1138 change getprop interface
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/GetVerticesExecutor.cpp
  src/planner/match/MatchSolver.cpp
  src/planner/ngql/PathPlanner.cpp
  src/planner/ngql/PathPlanner.h
  src/planner/plan/Query.cpp
  src/planner/plan/Query.h
  src/util/SchemaUtil.cpp
  src/util/SchemaUtil.h
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchEdgesValidator.h
  src/validator/FetchVerticesValidator.cpp
  src/validator/FetchVerticesValidator.h
  src/validator/GetSubgraphValidator.cpp
  src/validator/GetSubgraphValidator.h
  src/validator/GoValidator.cpp
  src/validator/GoValidator.h
  src/validator/test/FetchEdgesTest.cpp
  src/validator/test/FetchVerticesTest.cpp
  src/validator/test/ValidatorTestBase.cpp
Labels: ready-for-testing

#1144 fixed bug for drop space when ft index exists
  src/executor/admin/SpaceExecutor.cpp
Labels: ready-for-testing

#1141 Fix compile error
  src/planner/plan/PlanNode.h
Labels: ready-for-testing

#1092 Add time zone information in auth response.
  src/service/GraphService.cpp
Labels: ready-for-testing

#1154 fix typo
  src/executor/StorageAccessExecutor.h
  tests/tck/features/insert/Insert.feature
Labels: ready-for-testing

#1153 Fix test failed
  tests/job/test_session.py
  tests/tck/conftest.py
  tests/tck/features/insert/Insert.feature
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing

#1129 disable create space without vid_type
  src/parser/AdminSentences.h
  src/validator/AdminValidator.cpp
  src/validator/test/AdminValidatorTest.cpp
  src/validator/test/MaintainValidatorTest.cpp
  tests/admin/test_parts.py
  tests/admin/test_permission.py
  tests/admin/test_space.py
  tests/admin/test_users.py
  tests/job/test_session.py
  tests/query/stateless/test_if_exists.py
  tests/query/stateless/test_keyword.py
  tests/query/stateless/test_range.py
  tests/query/stateless/test_schema.py
  tests/tck/features/admin/Hosts.feature
  tests/tck/features/schema/Comment.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/user/User.feature
Labels: doc affected, incompatible, ready-for-testing

#764 Optimize/lifetime
  src/context/ExecutionContext.cpp
  src/context/ExecutionContext.h
  src/context/Result.h
  src/context/Symbols.h
  src/executor/Executor.cpp
  src/executor/Executor.h
  src/executor/query/AssignExecutor.cpp
  src/executor/query/DedupExecutor.cpp
  src/executor/query/FilterExecutor.cpp
  src/executor/query/IntersectExecutor.cpp
  src/executor/query/LimitExecutor.cpp
  src/executor/query/MinusExecutor.cpp
  src/executor/query/SetExecutor.cpp
  src/executor/query/SetExecutor.h
  src/executor/query/SortExecutor.cpp
  src/executor/query/TopNExecutor.cpp
  src/executor/test/TestMain.cpp
  src/planner/plan/Maintain.cpp
  src/planner/plan/Maintain.h
  src/planner/plan/PlanNode.h
  src/scheduler/AsyncMsgNotifyBasedScheduler.cpp
  src/scheduler/CMakeLists.txt
  src/scheduler/Scheduler.cpp
  src/scheduler/Scheduler.h
Labels: hi-pri, need to discuss, ready-for-testing

#1111 refactor go
  src/context/Iterator.h
  src/context/ast/QueryAstContext.h
  src/planner/CMakeLists.txt
  src/planner/PlannersRegister.cpp
  src/planner/PlannersRegister.h
  src/planner/ngql/GoPlanner.cpp
  src/planner/ngql/GoPlanner.h
  src/util/QueryUtil.cpp
  src/util/QueryUtil.h
  src/validator/GoValidator.cpp
  src/validator/GoValidator.h
  src/validator/TraversalValidator.cpp
  src/validator/test/QueryValidatorTest.cpp
  src/validator/test/SymbolsTest.cpp
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/optimizer/PushFilterDownLeftJoinRule.feature
Labels: ready-for-testing

#989 add go step limit OR sample (validate)
  src/context/ast/QueryAstContext.h
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/validator/GoValidator.cpp
  src/validator/GoValidator.h
  tests/tck/features/go/GO.feature
Labels: med-pri, new feature, ready-for-testing

#1149 fix the bug create space on group
  src/parser/AdminSentences.h
  src/validator/AdminValidator.cpp
Labels: ready-for-testing

#1108 Required python 3.7 for test framework
  tests/Makefile
  tests/README.md
  tests/tck/utils/nbv.py
Labels: ready-for-testing

#1165 Fix permission when use multi sentences with use space
  src/service/PermissionCheck.cpp
  src/service/PermissionCheck.h
  src/service/PermissionManager.cpp
  src/service/PermissionManager.h
  src/validator/Validator.h
  tests/admin/test_permission.py
Labels: bug, ready-for-testing

#1176 Update the error code.
  src/service/GraphService.cpp
  src/service/GraphService.h
Labels: ready-for-testing

#1182 Modify require cmake version and modify the tests
  CMakeLists.txt
  tests/Makefile
  tests/job/test_session.py
Labels: ready-for-testing

#1185 Fix the error when list slicing with null bound.
  src/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/bugfix/ListSlicingWithNull.feature
Labels: bug, ready-for-testing

#1186 fix agg type check when nested
  src/validator/GroupByValidator.cpp
  src/validator/GroupByValidator.h
  tests/tck/features/aggregate/Agg.feature
Labels: bug, ready-for-testing

#1079 add gflags to switch octal escape char support
  resources/gflags.json
  src/parser/scanner.lex
  src/service/GraphFlags.cpp
  src/service/GraphFlags.h
  tests/admin/test_configs.py
Labels: bug, ready-for-testing
