Repository vesoft-inc/nebula-graph, pull requests merged in 2021-07, with the labels that each got.

#1179 Expose time utils.
  src/daemons/GraphDaemon.cpp
  src/executor/admin/SessionExecutor.h
  src/executor/admin/SubmitJobExecutor.cpp
  src/optimizer/Optimizer.h
  src/optimizer/rule/IndexScanRule.cpp
  src/scheduler/AsyncMsgNotifyBasedScheduler.cpp
  src/service/GraphService.cpp
Labels: ready-for-testing

#1192 Fix build error when using clang
  src/scheduler/AsyncMsgNotifyBasedScheduler.cpp
Labels: ready-for-testing

#1183 support tck to test remote nebula graph
  tests/nebula-test-run.py
Labels: ready-for-testing

#1086 Fix extract filter visitor bug
  src/visitor/ExtractFilterExprVisitor.cpp
  src/visitor/test/CMakeLists.txt
  src/visitor/test/DeduceTypeVisitorTest.cpp
  src/visitor/test/ExtractFilterExprVisitorTest.cpp
  src/visitor/test/FilterTransformTest.cpp
  src/visitor/test/FoldConstantExprVisitorTest.cpp
  src/visitor/test/RewriteRelExprVisitorTest.cpp
  src/visitor/test/RewriteUnaryNotExprVisitorTest.cpp
  src/visitor/test/VisitorTestBase.h
Labels: ready-for-testing

#1085 Return all rules when execution plan is not stable
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/LeftJoinExecutor.cpp
  src/optimizer/OptContext.h
  src/optimizer/OptGroup.cpp
  src/optimizer/OptGroup.h
  src/optimizer/Optimizer.cpp
  src/optimizer/Optimizer.h
  src/optimizer/rule/IndexScanRule.cpp
  src/optimizer/rule/IndexScanRule.h
  src/visitor/ExprVisitorImpl.cpp
  tests/tck/features/optimizer/PushFilterDownAggregateRule.feature
  tests/tck/features/optimizer/PushFilterDownProjectRule.feature
Labels: ready-for-testing

#1193 Fix make down without stopping another graphd
  tests/common/nebula_service.py
Labels: ready-for-testing

#1152 Slow query.
  src/context/QueryContext.h
  src/context/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/executor/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/admin/KillQueryExecutor.cpp
  src/executor/admin/KillQueryExecutor.h
  src/executor/admin/ShowQueriesExecutor.cpp
  src/executor/admin/ShowQueriesExecutor.h
  src/executor/test/CMakeLists.txt
  src/executor/test/ShowQueriesTest.cpp
  src/optimizer/test/CMakeLists.txt
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/CMakeLists.txt
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  src/planner/plan/Admin.cpp
  src/planner/plan/Admin.h
  src/planner/plan/PlanNode.cpp
  src/planner/plan/PlanNode.h
  src/planner/test/CMakeLists.txt
  src/service/GraphService.cpp
  src/service/GraphService.h
  src/service/PermissionCheck.cpp
  src/service/QueryInstance.cpp
  src/service/RequestContext.h
  src/session/CMakeLists.txt
  src/session/ClientSession.cpp
  src/session/ClientSession.h
  src/session/GraphSessionManager.cpp
  src/session/GraphSessionManager.h
  src/util/ExpressionUtils.cpp
  src/util/test/CMakeLists.txt
  src/validator/AdminValidator.cpp
  src/validator/AdminValidator.h
  src/validator/GroupByValidator.h
  src/validator/LimitValidator.h
  src/validator/OrderByValidator.h
  src/validator/Validator.cpp
  src/validator/test/CMakeLists.txt
  src/visitor/test/CMakeLists.txt
  tests/Makefile
  tests/common/nebula_service.py
  tests/conftest.py
  tests/job/test_session.py
  tests/nebula-test-run.py
  tests/tck/conftest.py
  tests/tck/slowquery/KillSlowQueryViaDiffrentService.feature
  tests/tck/slowquery/KillSlowQueryViaSameService.feature
  tests/tck/steps/test_kill_slow_query_via_different_service.py
  tests/tck/steps/test_kill_slow_query_via_same_service.py
Labels: depend on common, depend on storage, doc affected, ready-for-testing

#1123 rebuild fulltext indexes via listener
  src/parser/AdminSentences.cpp
  src/parser/parser.yy
  src/validator/AdminJobValidator.h
Labels: doc affected, ready-for-testing

#1113 Let the test cases reentrant.
  tests/admin/test_configs.py
  tests/admin/test_permission.py
  tests/admin/test_space.py
  tests/admin/test_users.py
  tests/common/utils.py
Labels: ready-for-testing

#1170 detailed result of show index
  src/executor/maintain/EdgeIndexExecutor.cpp
  src/executor/maintain/TagIndexExecutor.cpp
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/planner/plan/Maintain.h
  src/validator/MaintainValidator.cpp
  src/validator/MaintainValidator.h
  tests/query/stateless/test_index.py
  tests/tck/conftest.py
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/index/Index.feature
  tests/tck/features/index/TagEdgeIndex.feature
Labels: doc affected, incompatible, ready-for-testing

#1200 Move the handle of sessionId is 0
  src/service/GraphService.cpp
  src/session/GraphSessionManager.cpp
Labels: ready-for-testing

#1198 Support to use get subgraph before pipe
  src/planner/Planner.cpp
  src/planner/Planner.h
  src/validator/GetSubgraphValidator.cpp
  src/validator/GetSubgraphValidator.h
  tests/tck/features/bugfix/SubgraphBeforePipe.feature
Labels: bug, ready-for-testing

#1204 Do not upload killed queries when queries have not sync to meta.
  src/executor/admin/KillQueryExecutor.cpp
  src/executor/admin/KillQueryExecutor.h
Labels: ready-for-testing

#1201 fix tck test,using remote address
  tests/nebula-test-run.py
Labels: ready-for-testing

#1206 [Minor] Remove unused variable definition in TCK
  tests/tck/features/bugfix/SubgraphBeforePipe.feature
Labels: ready-for-testing

#1205 Add full index scan rules into default ruleset in optimizer
  src/optimizer/OptimizerUtils.cpp
  src/optimizer/rule/EdgeIndexFullScanRule.cpp
  src/optimizer/rule/PushFilterDownEdgeIndexScanRule.cpp
  src/optimizer/rule/PushFilterDownEdgeIndexScanRule.h
  src/optimizer/rule/PushFilterDownTagIndexScanRule.cpp
  src/optimizer/rule/PushFilterDownTagIndexScanRule.h
  src/optimizer/rule/TagIndexFullScanRule.cpp
  src/optimizer/rule/UnionAllEdgeIndexScanRule.cpp
  src/optimizer/rule/UnionAllTagIndexScanRule.cpp
Labels: ready-for-testing

#1223 Increase the wait time for slow query test.
  tests/tck/slowquery/KillSlowQueryViaDiffrentService.feature
  tests/tck/slowquery/KillSlowQueryViaSameService.feature
Labels: ready-for-testing

#1217 [Minor] Add cases from Issue
  src/optimizer/OptimizerUtils.cpp
  tests/tck/features/bugfix/StringFlaotAddition.feature
Labels: depend on common, ready-for-testing

#1237 Return actual type if the case expr returns the same types.
  src/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/expression/Case.feature
Labels: ready-for-testing

#1235 fix multi-shortestPath bug
  src/executor/algo/ProduceSemiShortestPathExecutor.cpp
Labels: bug, ready-for-testing

#1245 tiny improve for updateSessionsToMeta
  src/session/GraphSessionManager.cpp
Labels: ready-for-testing

#1219 fix compilation error in some third-party versions
  src/planner/ngql/GoPlanner.cpp
  src/planner/ngql/PathPlanner.cpp
Labels: ready-for-testing

#1229 fix explicit group by user defined var
  src/validator/GroupByValidator.cpp
  tests/tck/features/aggregate/Agg.feature
Labels: ready-for-testing

#1240 fix filter degradation
  src/planner/match/WhereClausePlanner.cpp
  src/planner/match/WhereClausePlanner.h
  src/planner/match/WithClausePlanner.cpp
  src/planner/plan/Query.cpp
  tests/tck/features/match/With.feature
Labels: ready-for-testing

#1226 Add the case for null properties exists.
  tests/tck/features/expression/Predicate.feature
Labels: bug, ready-for-testing

#1230 [issue 1066]: enhance service script to return version information for '-v' option
  scripts/nebula.service
  scripts/utils.sh
Labels: ready-for-testing

#1233 [Minor] Add job-related pytest
  tests/Makefile
  tests/job/test_jobs.py
Labels: ready-for-testing

#1254 Fix jobs pytest failure
  tests/job/test_jobs.py
Labels: ready-for-testing

#1253 Dedup vertex/edge before delete.
  src/executor/Executor.cpp
  src/executor/mutate/DeleteExecutor.cpp
  src/executor/query/DedupExecutor.cpp
  src/planner/plan/Mutate.cpp
  src/planner/plan/Mutate.h
  src/validator/MutateValidator.cpp
  src/validator/test/MutateValidatorTest.cpp
Labels: bug, ready-for-testing

#1257 fix agg filter check in with clause
  src/parser/Clauses.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/parser.yy
  src/validator/YieldValidator.cpp
  tests/tck/features/aggregate/Agg.feature
Labels: ready-for-testing

#1250 Push edge related filters into GetNeighbors
  src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
  src/optimizer/rule/PushFilterDownGetNbrsRule.h
  tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
Labels: ready-for-testing

#1259 fix unionAllEdgeIndexScanRule
  src/optimizer/OptimizerUtils.cpp
  src/optimizer/rule/UnionAllIndexScanBaseRule.cpp
Labels: ready-for-testing

#1258 fix alias check in with clause
  src/validator/MatchValidator.cpp
  tests/tck/features/match/With.feature
Labels: ready-for-testing

#1260 Specify full index scan when using != as filter
  src/optimizer/CMakeLists.txt
  src/optimizer/OptimizerUtils.cpp
  src/optimizer/rule/OptimizeEdgeIndexScanByFilterRule.cpp
  src/optimizer/rule/OptimizeEdgeIndexScanByFilterRule.h
  src/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
  src/optimizer/rule/OptimizeTagIndexScanByFilterRule.h
Labels: ready-for-testing

#1266 Replace Slack home page with Slack invitation
  README.md
Labels: ready-for-testing

#1251 Add support in using relational expressions as filters in LOOKUP clause
  src/validator/LookupValidator.cpp
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/EdgeIndexFullScan.feature
  tests/tck/features/lookup/TagIndexFullScan.feature
Labels: doc affected, ready-for-testing

#1273 Fix the go return bad_type when the vertex without the tag
  src/context/Iterator.cpp
  tests/tck/features/go/GO.feature
Labels: bug, ready-for-testing

#1277 fix util functions
  src/executor/test/FilterTest.cpp
  src/optimizer/rule/PushFilterDownLeftJoinRule.cpp
  src/optimizer/rule/PushFilterDownProjectRule.cpp
  src/planner/match/LabelIndexSeek.cpp
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/util/test/ExpressionUtilsTest.cpp
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchVerticesValidator.cpp
  src/validator/FindPathValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/GroupByValidator.cpp
  src/validator/LookupValidator.cpp
  src/validator/MaintainValidator.cpp
  src/validator/MatchValidator.cpp
  src/validator/YieldValidator.cpp
  src/visitor/test/FilterTransformTest.cpp
  src/visitor/test/RewriteRelExprVisitorTest.cpp
  src/visitor/test/RewriteUnaryNotExprVisitorTest.cpp
Labels: ready-for-testing

#1276 eliminate one copy overhead in ExtractList of UnwindExecutor
  src/executor/query/UnwindExecutor.cpp
  src/executor/query/UnwindExecutor.h
Labels: ready-for-testing

#1281 Support more complete * syntax in WITH and RETURN
  src/parser/MatchSentence.cpp
  src/parser/MatchSentence.h
  src/parser/parser.yy
  src/validator/MatchValidator.cpp
  src/validator/MatchValidator.h
  tests/tck/features/match/Base.feature
  tests/tck/features/match/With.feature
Labels: ready-for-testing

#1271 Add more format of datetime.
  tests/tck/features/expression/FunctionCall.feature
Labels: ready-for-testing

#1291 Check whether index is valid at runtime
  src/executor/query/IndexScanExecutor.cpp
  tests/tck/features/lookup/LookUp.IntVid.feature
  tests/tck/features/lookup/LookUp.feature
Labels: ready-for-testing

#1282 [OptRule] Collapse continuous Project plan node
  src/optimizer/CMakeLists.txt
  src/optimizer/rule/CollapseProjectRule.cpp
  src/optimizer/rule/CollapseProjectRule.h
  src/optimizer/rule/PushFilterDownAggregateRule.cpp
  tests/tck/features/optimizer/CollapseProjectRule.feature
  tests/tck/features/optimizer/PushFilterDownLeftJoinRule.feature
Labels: ready-for-testing

#1294 small change for FindVisitor
  src/visitor/FindVisitor.cpp
  src/visitor/FindVisitor.h
Labels: do not review, ready-for-testing

#1268 Support get attribute of date/time/datetime.
  src/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/expression/Attribute.feature
Labels: doc affected, ready-for-testing

#1243 Replace the lastUser by user count.…
  src/context/Symbols.h
  src/executor/Executor.cpp
  src/scheduler/AsyncMsgNotifyBasedScheduler.cpp
  src/scheduler/Scheduler.cpp
Labels: enhancement, ready-for-testing

#1298 fix ci crash
  src/planner/match/MatchPlanner.cpp
  src/planner/match/MatchPlanner.h
  src/validator/YieldValidator.cpp
Labels: ready-for-testing
