Repository vesoft-inc/nebula-graph, pull requests merged in 2021-01, with the labels that each got.

#549 Fix GetNeighborsExecutor empty input result
  src/executor/query/GetNeighborsExecutor.cpp
Labels: ready-for-testing

#542 fix limit/offset
  src/parser/parser.yy
  tests/tck/features/go/GO.feature
Labels: bug, ready-for-review, ready-for-testing

#557 Fix mem leak in list comprehension.
  src/parser/parser.yy
Labels: ready-for-testing

#550 Erase by swap in filter.
  src/context/Iterator.h
  src/context/test/IteratorTest.cpp
  src/executor/algo/ConjunctPathExecutor.cpp
  src/executor/query/DedupExecutor.cpp
  src/executor/query/FilterExecutor.cpp
  src/executor/query/IntersectExecutor.cpp
  src/executor/query/MinusExecutor.cpp
Labels: ready-for-testing

#558 add assign executor
  src/executor/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/query/AssignExecutor.cpp
  src/executor/query/AssignExecutor.h
  src/executor/test/AssignTest.cpp
  src/executor/test/CMakeLists.txt
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/planner/Query.cpp
  src/planner/Query.h
Labels: ready-for-testing

#561 Optimize/add explicit move copy ctor
  src/context/Iterator.cpp
  src/context/Iterator.h
Labels: ready-for-testing

#532 Check address sanitizer in github action
  .github/workflows/pull_request.yml
  .gitignore
  tests/.gitignore
  tests/Makefile
  tests/common/dataset_printer.py
  tests/common/types.py
  tests/tck/conftest.py
  tests/tck/features/delete/DeleteEdge.IntVid.feature
  tests/tck/features/delete/DeleteEdge.feature
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/delete/DeleteVertex.feature
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/update/Update.IntVid.feature
  tests/tck/features/update/Update.feature
Labels: ready-for-testing

#541 Move schema test to tck and add more test for alter
  tests/maintain/test_tag_edge.py
  tests/tck/conftest.py
  tests/tck/features/schema/Schema.feature
Labels: ready-for-testing

#562 Add some todo case for lookup by index.
  src/validator/LookupValidator.cpp
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/LookUp.feature
Labels: ready-for-testing

#528 [testcase] add groupby & limit test cases
  tests/query/v1/test_groupby.py
  tests/tck/features/go/GroupbyLimit.IntVid.feature
  tests/tck/features/go/GroupbyLimit.feature
Labels: ready-for-testing

#566 Add the noexcept modifier for the move ctor/assign to avoid the perfo…
  src/context/Iterator.h
Labels: ready-for-testing

#564 update dockerfile expose port
  Dockerfile
Labels: ready-for-testing

#570 Add the int vid cases for match seek by tag.
  tests/tck/features/match/SeekByTag.intVid.feature
Labels: ready-for-testing

#563 Support to specify space name when creating a new space
  src/daemons/GraphDaemon.cpp
  tests/Makefile
  tests/common/comparator.py
  tests/common/utils.py
  tests/tck/conftest.py
  tests/tck/features/delete/DeleteEdge.feature
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
  tests/tck/utils/table.py
Labels: ready-for-testing

#577 Move starts/ends with and label expression tests to TCK framework
  tests/query/v2/test_label_expr.py
  tests/query/v2/test_starts_ends_with.py
  tests/tck/features/expression/EndsWith.feature
  tests/tck/features/expression/LabelExpr.feature
  tests/tck/features/expression/StartsWith.feature
Labels: ready-for-testing

#578 Increase the client timeout for test.
  tests/conftest.py
Labels: in progress, ready-for-testing

#565 Add the multiple tags for match node.
  src/context/ast/QueryAstContext.h
  src/parser/MatchSentence.cpp
  src/parser/MatchSentence.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/planner/match/LabelIndexSeek.cpp
  src/planner/match/LabelIndexSeek.h
  src/planner/match/PropIndexSeek.cpp
  src/planner/match/VertexIdSeek.cpp
  src/validator/MatchValidator.cpp
  src/validator/MatchValidator.h
  tests/tck/conftest.py
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
Labels: ready-for-testing

#583 Improve project explained columns format and Fix compile errors
  src/context/test/CMakeLists.txt
  src/executor/test/CMakeLists.txt
  src/optimizer/test/CMakeLists.txt
  src/parser/test/CMakeLists.txt
  src/planner/Query.cpp
  src/util/test/CMakeLists.txt
  src/validator/test/CMakeLists.txt
  src/visitor/test/CMakeLists.txt
Labels: ready-for-testing

#572 fixed bug of invalid expression expression caused graph crash
  src/validator/LookupValidator.cpp
  src/validator/test/LookupValidatorTest.cpp
Labels: ready-for-review, ready-for-testing

#582 Optimize/keep same result for int string vid cases
  tests/tck/conftest.py
  tests/tck/features/delete/DeleteEdge.IntVid.feature
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/fetch/FetchEdges.intVid.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GroupbyLimit.IntVid.feature
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/Output.intVid.feature
  tests/tck/features/lookup/WithYield.intVid.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/SeekByTag.intVid.feature
  tests/tck/features/yield/yield.IntVid.feature
Labels: ready-for-review, ready-for-testing

#467 Support predicate expression.
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
  src/util/ParserUtil.h
  src/visitor/CollectAllExprsVisitor.cpp
  src/visitor/CollectAllExprsVisitor.h
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/DeduceTypeVisitor.h
  src/visitor/ExprVisitorImpl.cpp
  src/visitor/ExprVisitorImpl.h
  src/visitor/FindAnyExprVisitor.cpp
  src/visitor/FindAnyExprVisitor.h
  src/visitor/FoldConstantExprVisitor.cpp
  src/visitor/FoldConstantExprVisitor.h
  src/visitor/RewriteInputPropVisitor.cpp
  src/visitor/RewriteInputPropVisitor.h
  src/visitor/RewriteLabelAttrVisitor.cpp
  src/visitor/RewriteLabelAttrVisitor.h
  src/visitor/RewriteMatchLabelVisitor.cpp
  src/visitor/RewriteMatchLabelVisitor.h
  src/visitor/RewriteSymExprVisitor.cpp
  src/visitor/RewriteSymExprVisitor.h
  tests/tck/features/expression/predicate.feature
Labels: ready-for-testing

#596 Add option t for package.
  package/package.sh
Labels: ready-for-testing

#585 fix getNeighbor iterator
  src/context/Iterator.cpp
  src/context/Iterator.h
  tests/query/v2/test_in_not_in.py
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: bug, ready-for-testing

#620 Correct the cases.
  tests/admin/test_configs.py
Labels: ready-for-testing

#618 Enhance the dedup with calling emplace once.
  src/executor/query/DedupExecutor.cpp
Labels: ready-for-testing

#553 Fix match return vertex undefined labels
  src/context/Iterator.cpp
  src/parser/parser.yy
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/MatchClausePlanner.h
  src/validator/FetchVerticesValidator.cpp
  src/validator/FetchVerticesValidator.h
  src/validator/GetSubgraphValidator.cpp
  src/validator/MatchValidator.cpp
  src/validator/test/MockSchemaManager.h
  tests/tck/features/bugfix/MatchReturnEmptyTag.feature
Labels: bug, ready-for-review, ready-for-testing

#633 Modify error msg
  tests/tck/features/schema/Schema.feature
  tests/tck/features/user/User.feature
Labels: ready-for-testing

#600 Support to rebuild multi indexes or all
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/validator/AdminJobValidator.cpp
  tests/tck/features/index/Index.feature
Labels: doc required, ready-for-testing

#631 add agg functions
  src/parser/parser.yy
  src/parser/scanner.lex
  tests/tck/features/agg/Agg.feature
Labels: doc required, ready-for-review, ready-for-testing

#606 Support match 0 to n steps
  src/planner/match/Expand.cpp
  src/planner/match/Expand.h
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/MatchClausePlanner.h
  src/planner/match/MatchSolver.cpp
  src/planner/match/MatchSolver.h
  src/planner/match/VertexIdSeek.cpp
  src/validator/MatchValidator.cpp
  tests/tck/features/bugfix/MatchReturnEmptyTag.feature
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/ZeroStep.feature
  tests/tck/features/match/ZeroStep.intVid.feature
Labels: ready-for-testing

#628 Reserve capacity in some cases.
  src/executor/query/DataCollectExecutor.cpp
  src/executor/query/DedupExecutor.cpp
  src/executor/query/ProjectExecutor.cpp
Labels: ready-for-testing

#630 fix groupby
  src/validator/GroupByValidator.cpp
  tests/tck/features/agg/Agg.feature
Labels: ready-for-review, ready-for-testing

#607 [PTAL] Match groupby
  src/context/ast/QueryAstContext.h
  src/executor/query/AggregateExecutor.cpp
  src/planner/CMakeLists.txt
  src/planner/match/ReturnClausePlanner.cpp
  src/planner/match/YieldClausePlanner.cpp
  src/planner/match/YieldClausePlanner.h
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/validator/GroupByValidator.cpp
  src/validator/GroupByValidator.h
  src/validator/MatchValidator.cpp
  src/validator/MatchValidator.h
  src/validator/test/MatchValidatorTest.cpp
  src/visitor/RewriteMatchLabelVisitor.cpp
  src/visitor/RewriteMatchLabelVisitor.h
  tests/tck/features/expression/predicate.feature
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/match/MatchGroupBy.feature
  tests/tck/features/schema/Schema.feature
Labels: enhancement, ready-for-review, ready-for-testing

#629 move v1 fetch cases to tck
  tests/query/v1/test_fetch_edges.py
  tests/query/v1/test_fetch_empty.py
  tests/query/v1/test_fetch_vertex.py
  tests/tck/features/fetch/FetchEdges.intVid.feature
  tests/tck/features/fetch/FetchEdges.strVid.feature
  tests/tck/features/fetch/FetchEmptyProps.strVid.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
Labels: ready-for-testing

#625 Adapt the max return edge.
  src/optimizer/rule/LimitPushDownRule.cpp
  src/planner/Query.h
Labels: ready-for-testing

#623 fix assign error
  src/executor/query/AssignExecutor.cpp
Labels: ready-for-testing

#589 Support execution plan validation in test framework
  tests/common/plan_differ.py
  tests/query/v2/test_optimizer.py
  tests/tck/conftest.py
  tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
  tests/tck/features/optimizer/PushLimitDownRule.feature
  tests/tck/features/optimizer/TopNRule.feature
Labels: ready-for-testing

#647 sort go test result
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
Labels: ready-for-testing

#640 Fix the error messge for expr to string.
  src/optimizer/rule/IndexScanRule.cpp
Labels: ready-for-review, ready-for-testing

#622 add subgraph test case
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: ready-for-testing

#627 Let fetch prop on tag return VERTEX
  src/executor/query/GetVerticesExecutor.cpp
  src/validator/FetchVerticesValidator.cpp
  src/validator/FetchVerticesValidator.h
  src/validator/test/FetchVerticesTest.cpp
  src/validator/test/LookupValidatorTest.cpp
  tests/maintain/test_tag_edge.py
  tests/mutate/test_insert_1.py
  tests/mutate/test_insert_2.py
  tests/query/v2/test_basic_type_crud.py
  tests/tck/features/fetch/FetchEmpty.feature
  tests/tck/features/fetch/FetchEmptyProps.strVid.feature
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/ttl/TTL.feature
  tests/tck/features/update/Update.IntVid.feature
  tests/tck/features/update/Update.feature
Labels: ready-for-testing

#619 Fix bug about match index selection
  src/planner/match/PropIndexSeek.cpp
  src/planner/match/VertexIdSeek.cpp
  src/planner/match/VertexIdSeek.h
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
Labels: bug, ready-for-testing

#641 Let fetch prop on edge return EDGE
  src/executor/query/GetEdgesExecutor.cpp
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchEdgesValidator.h
  src/validator/test/FetchEdgesTest.cpp
  tests/query/v1/__init__.py
  tests/query/v1/test_yield.py
  tests/query/v2/test_basic_type_crud.py
  tests/tck/features/bugfix/MatchReturnEmptyTag.feature
  tests/tck/features/fetch/FetchEdges.intVid.feature
  tests/tck/features/fetch/FetchEdges.strVid.feature
  tests/tck/features/fetch/FetchEmpty.feature
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/ttl/TTL.feature
  tests/tck/features/update/Update.IntVid.feature
  tests/tck/features/update/Update.feature
Labels: ready-for-testing

#423 Create space with zone
  src/executor/admin/SpaceExecutor.cpp
  src/executor/query/IndexScanExecutor.cpp
  src/parser/AdminSentences.h
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/validator/AdminValidator.cpp
  tests/admin/test_space.py
Labels: doc required, ready-for-review, ready-for-testing

#479 Support reduce expression
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ScannerTest.cpp
  src/util/ParserUtil.h
  src/visitor/CollectAllExprsVisitor.cpp
  src/visitor/CollectAllExprsVisitor.h
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/DeduceTypeVisitor.h
  src/visitor/ExprVisitorImpl.cpp
  src/visitor/ExprVisitorImpl.h
  src/visitor/FindAnyExprVisitor.cpp
  src/visitor/FindAnyExprVisitor.h
  src/visitor/FoldConstantExprVisitor.cpp
  src/visitor/FoldConstantExprVisitor.h
  src/visitor/RewriteInputPropVisitor.cpp
  src/visitor/RewriteInputPropVisitor.h
  src/visitor/RewriteLabelAttrVisitor.cpp
  src/visitor/RewriteLabelAttrVisitor.h
  src/visitor/RewriteMatchLabelVisitor.cpp
  src/visitor/RewriteMatchLabelVisitor.h
  src/visitor/RewriteSymExprVisitor.cpp
  src/visitor/RewriteSymExprVisitor.h
  tests/tck/features/expression/reduce.feature
Labels: doc required, ready-for-testing

#661 Fix segments equal_to.
  src/context/Iterator.cpp
  src/context/Iterator.h
  src/context/test/IteratorTest.cpp
  src/executor/algo/CartesianProductExecutor.cpp
  src/executor/query/DataCollectExecutor.cpp
  src/executor/query/DataJoinExecutor.cpp
Labels: bug, ready-for-testing

#682 Add host stats.
  src/executor/Executor.cpp
  src/executor/Executor.h
  src/executor/StorageAccessExecutor.h
  src/executor/mutate/DeleteExecutor.h
  src/executor/mutate/InsertExecutor.h
  src/executor/mutate/UpdateExecutor.h
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetNeighborsExecutor.h
  src/executor/query/GetPropExecutor.h
  src/executor/query/GetVerticesExecutor.cpp
  src/executor/query/IndexScanExecutor.h
Labels: ready-for-testing

#683 Print date time when show jobs.
  src/executor/admin/SubmitJobExecutor.cpp
Labels: ready-for-testing

#684 ut add path filter by dst node
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/match/VariableLengthPattern.intVid.feature
Labels: ready-for-testing

#692 index case
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/index/Index.feature
Labels: ready-for-testing
