Repository vesoft-inc/nebula-graph, pull requests merged in 2021-03, with the labels that each got.

#751 Reuse the the vertices ast structure.
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/MutateSentences.cpp
  src/parser/MutateSentences.h
  src/parser/TraverseSentences.cpp
  src/parser/TraverseSentences.h
  src/validator/FetchVerticesValidator.cpp
  src/validator/MutateValidator.cpp
Labels: ready-for-review, ready-for-testing

#760 return sentence
  src/parser/parser.yy
  tests/tck/features/yield/return.feature
Labels: ready-for-review, ready-for-testing

#767 fix where in go clause
  src/validator/GoValidator.cpp
  tests/tck/features/go/GO.feature
Labels: ready-for-review, ready-for-testing

#773 Improve join.
  src/context/Iterator.h
  src/executor/query/DataJoinExecutor.cpp
  src/executor/query/DataJoinExecutor.h
Labels: ready-for-testing

#765 Fix BUG: if flags are all true, remainedExpr_ will get invalid Logica…
  src/visitor/ExtractFilterExprVisitor.cpp
Labels: ready-for-testing

#776 Correct the invalid vid error message.
  src/executor/StorageAccessExecutor.h
  tests/tck/features/insert/Insert.feature
Labels: ready-for-review, ready-for-testing

#763 Add support to use Aggregation functions with WITH clause
  src/context/ast/QueryAstContext.h
  src/planner/match/WithClausePlanner.cpp
  src/planner/match/WithClausePlanner.h
  src/validator/MatchValidator.cpp
  src/validator/test/MatchValidatorTest.cpp
  tests/tck/features/match/WithUnwind.feature
Labels: enhancement, ready-for-review, ready-for-testing

#772 fix update/upsert
  src/validator/MutateValidator.cpp
  src/validator/test/MutateValidatorTest.cpp
  tests/tck/features/update/Update.feature
Labels: ready-for-review, ready-for-testing

#747 update readme links
  README-CN.md
  README.md
Labels: ready-for-review, ready-for-testing

#766 fix match where clause
  src/planner/match/WhereClausePlanner.cpp
  tests/tck/features/match/Base.feature
Labels: ready-for-review, ready-for-testing

#591 Make StartNode first when generating Execution Plan
  src/planner/SequentialPlanner.cpp
  src/validator/SequentialValidator.cpp
  src/validator/SequentialValidator.h
  src/validator/UseValidator.cpp
  src/validator/test/SymbolsTest.cpp
Labels: ready-for-testing

#780 Fix type length of string index column when show create tag index
  src/util/IndexUtil.cpp
  tests/tck/features/index/Index.feature
Labels: ready-for-testing

#753 Correct the git sha in http server.
  src/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/daemons/GraphDaemon.cpp
  src/planner/test/CMakeLists.txt
  src/service/QueryEngine.cpp
  src/validator/test/YieldValidatorTest.cpp
  src/version/CMakeLists.txt
  src/version/Version.cpp.in
  src/version/Version.h
Labels: bug, ready-for-review, ready-for-testing

#781 Fix explain validator subplan generation
  src/validator/ExplainValidator.cpp
Labels: ready-for-testing

#746 add type conversion tck cases
  tests/tck/features/expression/function/TypeConversion.feature
Labels: depend on common, ready-for-review, ready-for-testing

#785 disable_toss
  src/validator/AdminValidator.cpp
Labels: ready-for-review, ready-for-testing

#752 fix withClause
  src/executor/query/FilterExecutor.cpp
  src/planner/Query.h
  src/planner/match/WhereClausePlanner.cpp
  tests/tck/features/match/WithUnwind.feature
Labels: ready-for-review, ready-for-testing

#783 use local_ip OR hostName represent graph in meta
  src/service/GraphFlags.cpp
  src/service/GraphFlags.h
  src/service/QueryEngine.cpp
Labels: ready-for-testing

#679 Check dataflow dependency between plan nodes in optimizer
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  src/context/CMakeLists.txt
  src/context/Symbols.cpp
  src/context/Symbols.h
  src/optimizer/CMakeLists.txt
  src/optimizer/OptContext.cpp
  src/optimizer/OptContext.h
  src/optimizer/OptGroup.cpp
  src/optimizer/OptGroup.h
  src/optimizer/OptRule.cpp
  src/optimizer/OptRule.h
  src/optimizer/Optimizer.cpp
  src/optimizer/Optimizer.h
  src/optimizer/rule/IndexScanRule.cpp
  src/optimizer/rule/IndexScanRule.h
  src/optimizer/rule/LimitPushDownRule.cpp
  src/optimizer/rule/LimitPushDownRule.h
  src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
  src/optimizer/rule/PushFilterDownGetNbrsRule.h
  src/optimizer/rule/TopNRule.cpp
  src/optimizer/rule/TopNRule.h
  src/optimizer/test/IndexScanRuleTest.cpp
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/util/CMakeLists.txt
  src/util/GroupUtil.cpp
  src/util/GroupUtil.h
  src/util/Utils.h
  src/validator/test/ValidatorTestBase.cpp
Labels: ready-for-testing

#669 Add opt rules to delete redundant dedup and project plan node
  README.md
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetVerticesExecutor.cpp
  src/optimizer/CMakeLists.txt
  src/optimizer/OptContext.cpp
  src/optimizer/rule/MergeGetNbrsAndDedupRule.cpp
  src/optimizer/rule/MergeGetNbrsAndDedupRule.h
  src/optimizer/rule/MergeGetNbrsAndProjectRule.cpp
  src/optimizer/rule/MergeGetNbrsAndProjectRule.h
  src/optimizer/rule/MergeGetVerticesAndDedupRule.cpp
  src/optimizer/rule/MergeGetVerticesAndDedupRule.h
  src/optimizer/rule/MergeGetVerticesAndProjectRule.cpp
  src/optimizer/rule/MergeGetVerticesAndProjectRule.h
  src/planner/Logic.cpp
  src/planner/Logic.h
  src/planner/PlanNode.h
  src/planner/Query.cpp
  src/planner/Query.h
  src/util/SchemaUtil.cpp
  tests/Makefile
  tests/common/plan_differ.py
  tests/tck/features/agg/Agg.feature
  tests/tck/features/match/MatchGroupBy.feature
  tests/tck/features/optimizer/MergeGetNbrsDedupProjectRule.feature
  tests/tck/features/optimizer/MergeGetVerticesDedupProjectRule.feature
Labels: ready-for-testing

#779 if type_ is empty ignore it
  src/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: ready-for-testing

#790 Fix expand match execution plan in right direction
  src/planner/match/MatchClausePlanner.cpp
  src/validator/test/QueryValidatorTest.cpp
Labels: ready-for-testing

#758 add LeftJoin & change DataJoin to InnerJoin
  src/executor/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/query/DataJoinExecutor.cpp
  src/executor/query/DataJoinExecutor.h
  src/executor/query/InnerJoinExecutor.cpp
  src/executor/query/InnerJoinExecutor.h
  src/executor/query/JoinExecutor.cpp
  src/executor/query/JoinExecutor.h
  src/executor/query/LeftJoinExecutor.cpp
  src/executor/query/LeftJoinExecutor.h
  src/executor/test/CMakeLists.txt
  src/executor/test/DataJoinTest.cpp
  src/executor/test/JoinTest.cpp
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/planner/Query.cpp
  src/planner/Query.h
  src/planner/match/InnerJoinStrategy.cpp
  src/validator/GoValidator.cpp
  src/validator/test/GroupByValidatorTest.cpp
  src/validator/test/MatchValidatorTest.cpp
  src/validator/test/QueryValidatorTest.cpp
  src/validator/test/SymbolsTest.cpp
  tests/tck/features/optimizer/MergeGetNbrsDedupProjectRule.feature
Labels: ready-for-review, ready-for-testing

#784 Add support to compare different numerical types in LOOKUP WHERE clause
  src/validator/LookupValidator.cpp
  src/validator/LookupValidator.h
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
Labels: ready-for-review, ready-for-testing

#789 Enhance seq iter.
  src/context/Iterator.cpp
  src/context/Iterator.h
  src/context/test/IteratorTest.cpp
  src/executor/algo/CartesianProductExecutor.cpp
  src/executor/algo/CartesianProductExecutor.h
  src/executor/algo/ConjunctPathExecutor.cpp
  src/executor/query/DataCollectExecutor.cpp
  src/executor/query/DedupExecutor.cpp
  src/executor/query/InnerJoinExecutor.cpp
  src/executor/query/InnerJoinExecutor.h
  src/executor/query/IntersectExecutor.cpp
  src/executor/query/JoinExecutor.cpp
  src/executor/query/JoinExecutor.h
  src/executor/query/LeftJoinExecutor.cpp
  src/executor/query/LeftJoinExecutor.h
  src/executor/query/MinusExecutor.cpp
  src/executor/query/SetExecutor.cpp
  src/executor/query/SetExecutor.h
  src/executor/query/SortExecutor.cpp
  src/executor/query/TopNExecutor.cpp
  src/executor/query/TopNExecutor.h
  src/executor/query/UnionExecutor.cpp
  src/executor/test/JoinTest.cpp
  src/executor/test/SetExecutorTest.cpp
  src/validator/FindPathValidator.cpp
Labels: ready-for-testing

#616 Correct/ast tostring format
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/GraphScanner.h
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/MatchSentence.cpp
  src/parser/MutateSentences.cpp
  src/parser/TraverseSentences.cpp
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/service/QueryInstance.cpp
  src/util/AstUtils.h
  src/util/SchemaUtil.cpp
  src/util/test/ExpressionUtilsTest.cpp
  src/validator/GroupByValidator.cpp
  src/validator/test/FetchVerticesTest.cpp
  src/validator/test/ValidatorTestBase.h
  src/validator/test/YieldValidatorTest.cpp
  tests/tck/features/expression/EndsWith.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/expression/Reduce.feature
  tests/tck/features/expression/StartsWith.feature
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/update/Update.IntVid.feature
  tests/tck/features/update/Update.feature
  tests/tck/features/yield/NoSpaceChosen.feature
  tests/tck/features/yield/return.feature
  tests/tck/features/yield/yield.IntVid.feature
  tests/tck/features/yield/yield.feature
Labels: bug, ready-for-testing

#793 tck support insert NULL
  tests/common/csv_import.py
  tests/data/nba/player.csv
  tests/tck/features/match/Base.feature
Labels: ready-for-review, ready-for-testing

#792 Tune the expired time in ci.
  tests/common/nebula_service.py
Labels: in progress, ready-for-testing

#796 Response optimization time to client
  src/planner/ExecutionPlan.cpp
  src/planner/ExecutionPlan.h
  src/service/QueryInstance.cpp
Labels: ready-for-testing

#797 Refactor and cleanup
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetVerticesExecutor.cpp
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/planner/Planner.cpp
  src/planner/Planner.h
  src/planner/Query.cpp
  src/planner/Query.h
  src/planner/SequentialPlanner.cpp
  src/planner/match/MatchClausePlanner.cpp
  tests/common/csv_import.py
Labels: ready-for-testing

#731 add isNull/isNotNull
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/ParserTest.cpp
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/ExtractPropExprVisitor.cpp
  src/visitor/RewriteInputPropVisitor.cpp
  tests/tck/features/expression/UnaryExpr.feature
Labels: ready-for-review, ready-for-testing

#801 Fix get src prop dead loop in GetNeighborsIter.
  src/context/Iterator.cpp
  src/validator/GoValidator.cpp
Labels: ready-for-testing

#724 Fix RelationalExpression
  tests/tck/features/expression/RelationalExpr.feature
Labels: depend on common, ready-for-review, ready-for-testing

#791 Enhance prop iter.
  src/context/Iterator.cpp
  src/context/Iterator.h
  src/executor/Executor.cpp
  src/executor/Executor.h
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetVerticesExecutor.cpp
  src/executor/query/GetVerticesExecutor.h
  src/executor/query/IndexScanExecutor.cpp
  src/executor/query/InnerJoinExecutor.cpp
  src/executor/query/LeftJoinExecutor.cpp
  src/validator/GoValidator.cpp
  src/validator/test/GroupByValidatorTest.cpp
  src/validator/test/QueryValidatorTest.cpp
Labels: ready-for-testing

#815 Specify nebula service port range to avoid conflicts with client connection
  tests/common/nebula_service.py
Labels: ready-for-testing

#818 Fixed toString method of create index sentence
  src/parser/MaintainSentences.cpp
  src/parser/Sentence.h
  src/parser/test/ParserTest.cpp
Labels: ready-for-review, ready-for-testing

#817 Fix go explain.
  src/validator/GoValidator.cpp
Labels: ready-for-testing

#500 Enhance the match by id filter eval id.
  src/context/ast/QueryAstContext.h
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/VertexIdSeek.cpp
  src/visitor/CMakeLists.txt
  src/visitor/VidExtractVisitor.cpp
  src/visitor/VidExtractVisitor.h
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/SeekById.feature
  tests/tck/features/match/SeekById.intVid.feature
Labels: bug, ready-for-testing

#820 Improve join when single column.
  src/executor/query/InnerJoinExecutor.cpp
  src/executor/query/InnerJoinExecutor.h
  src/executor/query/JoinExecutor.cpp
  src/executor/query/JoinExecutor.h
  src/executor/query/LeftJoinExecutor.cpp
  src/executor/query/LeftJoinExecutor.h
Labels: ready-for-testing

#814 add tck case for In and notIn
  tests/tck/features/expression/RelationalExpr.feature
Labels: ready-for-testing

#788 upload package to artifact and OSS nightly
  .github/workflows/package.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#828 cherry pick #500, #820
  .github/workflows/package.yml
  .github/workflows/release.yml
  src/context/ast/QueryAstContext.h
  src/executor/query/InnerJoinExecutor.cpp
  src/executor/query/InnerJoinExecutor.h
  src/executor/query/JoinExecutor.cpp
  src/executor/query/JoinExecutor.h
  src/executor/query/LeftJoinExecutor.cpp
  src/executor/query/LeftJoinExecutor.h
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/VertexIdSeek.cpp
  src/visitor/CMakeLists.txt
  src/visitor/VidExtractVisitor.cpp
  src/visitor/VidExtractVisitor.h
  tests/tck/features/expression/RelationalExpr.feature
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/SeekById.feature
  tests/tck/features/match/SeekById.intVid.feature
Labels: ready-for-testing

#794 [bugfix] fix deduce type of in expression
  .gitignore
  src/visitor/DeduceTypeVisitor.cpp
  tests/tck/features/expression/In.feature
  tests/tck/features/expression/ListComprehension.feature
  tests/tck/features/expression/Predicate.feature
  tests/tck/features/expression/Reduce.feature
Labels: ready-for-review, ready-for-testing

#787 disable some combination of match clause
  src/planner/match/SegmentsConnector.cpp
  src/validator/MatchValidator.cpp
  tests/tck/features/match/Base.feature
Labels: ready-for-testing

#832 update default gflags to register
  resources/gflags.json
  tests/admin/test_configs.py
Labels: ready-for-review, ready-for-testing

#806 Release unused symbols for plan node when optimizing
  src/optimizer/OptGroup.cpp
  src/optimizer/OptGroup.h
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
Labels: ready-for-testing

#808 add exists
  src/parser/parser.yy
  src/planner/SequentialPlanner.cpp
  src/planner/match/MatchPlanner.cpp
  src/util/CMakeLists.txt
  src/util/ParserUtil.cpp
  src/util/ParserUtil.h
  src/validator/Validator.cpp
  src/visitor/CollectAllExprsVisitor.cpp
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/ExprVisitorImpl.cpp
  src/visitor/FindAnyExprVisitor.cpp
  src/visitor/FoldConstantExprVisitor.cpp
  src/visitor/RewriteInputPropVisitor.cpp
  src/visitor/RewriteLabelAttrVisitor.cpp
  src/visitor/RewriteMatchLabelVisitor.cpp
  src/visitor/RewriteSymExprVisitor.cpp
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/WithUnwind.feature
Labels: depend on common, ready-for-review, ready-for-testing

#826 fix test feature
  tests/tck/features/go/GO.feature
Labels: ready-for-review, ready-for-testing

#829 Fix the logical of space require for nested sentences.
  src/validator/AssignmentValidator.cpp
  src/validator/AssignmentValidator.h
  src/validator/ExplainValidator.cpp
  src/validator/PipeValidator.cpp
  src/validator/PipeValidator.h
  src/validator/SetValidator.cpp
  src/validator/SetValidator.h
  src/validator/Validator.h
  tests/tck/features/yield/NoSpaceChosen.feature
Labels: ready-for-review, ready-for-testing

#844 fix package
  .github/workflows/package.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#840 Move plan description from QueryContext to ExecutionPlan
  src/context/QueryContext.cpp
  src/context/QueryContext.h
  src/executor/Executor.cpp
  src/planner/ExecutionPlan.cpp
  src/planner/ExecutionPlan.h
  src/planner/PlanNode.h
  src/service/QueryInstance.cpp
  src/service/QueryInstance.h
  src/validator/ExplainValidator.cpp
Labels: ready-for-testing

#802 Refactor agg parser
  src/context/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/executor/test/CMakeLists.txt
  src/optimizer/test/CMakeLists.txt
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/CMakeLists.txt
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  src/util/ExpressionUtils.cpp
  src/util/test/CMakeLists.txt
  src/validator/GroupByValidator.cpp
  src/validator/test/CMakeLists.txt
  src/validator/test/GroupByValidatorTest.cpp
  src/validator/test/YieldValidatorTest.cpp
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/test/CMakeLists.txt
  tests/tck/features/agg/Agg.feature
  tests/tck/features/go/GroupbyLimit.IntVid.feature
  tests/tck/features/go/GroupbyLimit.feature
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/WithUnwind.feature
Labels: ready-for-review, ready-for-testing

#845 fix uploading to oss
  .github/workflows/package.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#851 Return partial succeeded.
  src/context/QueryContext.h
  src/executor/StorageAccessExecutor.h
  src/service/GraphService.cpp
Labels: ready-for-testing

#853 V2.0.0
  .github/workflows/package.yml
  .github/workflows/release.yml
  src/context/QueryContext.cpp
  src/context/QueryContext.h
  src/context/test/CMakeLists.txt
  src/daemons/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/StorageAccessExecutor.h
  src/executor/test/CMakeLists.txt
  src/optimizer/test/CMakeLists.txt
  src/parser/parser.yy
  src/parser/scanner.lex
  src/parser/test/CMakeLists.txt
  src/parser/test/ParserTest.cpp
  src/parser/test/ScannerTest.cpp
  src/planner/ExecutionPlan.cpp
  src/planner/ExecutionPlan.h
  src/planner/PlanNode.h
  src/service/GraphService.cpp
  src/service/QueryInstance.cpp
  src/service/QueryInstance.h
  src/util/ExpressionUtils.cpp
  src/util/test/CMakeLists.txt
  src/validator/AssignmentValidator.cpp
  src/validator/AssignmentValidator.h
  src/validator/ExplainValidator.cpp
  src/validator/GroupByValidator.cpp
  src/validator/PipeValidator.cpp
  src/validator/PipeValidator.h
  src/validator/SetValidator.cpp
  src/validator/SetValidator.h
  src/validator/Validator.h
  src/validator/test/CMakeLists.txt
  src/validator/test/GroupByValidatorTest.cpp
  src/validator/test/YieldValidatorTest.cpp
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/test/CMakeLists.txt
  tests/tck/features/agg/Agg.feature
  tests/tck/features/go/GroupbyLimit.IntVid.feature
  tests/tck/features/go/GroupbyLimit.feature
  tests/tck/features/match/MatchById.feature
  tests/tck/features/match/WithUnwind.feature
  tests/tck/features/yield/NoSpaceChosen.feature
Labels: ready-for-testing

#847 Store nullable data in a separate csv file
  tests/data/nba/config.yaml
  tests/data/nba/null.csv
  tests/data/nba/player.csv
  tests/query/bugs/fixed_pr2042.py
  tests/query/stateless/test_lookup.py
  tests/tck/conftest.py
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/update/Update.IntVid.feature
Labels: ready-for-testing

#861 fix oss uploading
  .github/workflows/package.yml
  .github/workflows/release.yml
Labels: ready-for-review, ready-for-testing

#863 [cherrypick]Oss
  .github/workflows/package.yml
  .github/workflows/release.yml
Labels: ready-for-testing

#854 add bit functions tck cases
  tests/tck/features/expression/function/Mathematical.feature
Labels: depend on common, ready-for-review, ready-for-testing

#859 fix getNeighborIter
  src/context/Iterator.cpp
  src/context/Iterator.h
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
Labels: ready-for-review, ready-for-testing

#849 Retry for queries related to schema modifications in CI
  .github/workflows/package.yml
  .github/workflows/pull_request.yml
  tests/Makefile
  tests/common/comparator.py
  tests/common/types.py
  tests/common/utils.py
  tests/tck/conftest.py
  tests/tck/features/bugfix/MatchReturnEmptyTag.feature
  tests/tck/features/delete/DeleteEdge.IntVid.feature
  tests/tck/features/delete/DeleteEdge.feature
  tests/tck/features/delete/DeleteVertex.IntVid.feature
  tests/tck/features/fetch/FetchEmpty.feature
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/index/Index.feature
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
  tests/tck/features/lookup/LookUp.IntVid.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/mutate/InsertWithTimeType.feature
  tests/tck/features/parser/Example.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/ttl/TTL.feature
  tests/tck/features/update/Update.IntVid.feature
  tests/tck/features/update/Update.feature
  tests/tck/features/user/User.feature
Labels: ready-for-testing

#873 Generate log directory, if it does not exist
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  src/daemons/GraphDaemon.cpp
Labels: ready-for-review, ready-for-testing

#855 Avoid build storage for graphd image building. And try the local modu…
  .dockerignore
  Dockerfile
  package/CMakeLists.txt
  package/package.sh
Labels: ready-for-testing

#881 Extract dedup vid request data logics
  .github/workflows/pull_request.yml
  src/executor/CMakeLists.txt
  src/executor/StorageAccessExecutor.cpp
  src/executor/StorageAccessExecutor.h
  src/executor/query/GetNeighborsExecutor.cpp
  src/executor/query/GetNeighborsExecutor.h
  src/executor/query/GetVerticesExecutor.cpp
  src/executor/test/GetNeighborsTest.cpp
Labels: ready-for-testing

#877 Cleanup pytest cases related to query module
  tests/pytest.ini
  tests/query/stateless/test_match_find.py
  tests/query/v2/__init__.py
  tests/query/v2/conftest.py
  tests/query/v2/match/__init__.py
  tests/query/v2/match/conftest.py
  tests/query/v2/match/test_variable_length_relationships.py
  tests/query/v2/test_basic_type_crud.py
  tests/query/v2/utils.py
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/match/ZeroStep2.feature
  tests/tck/features/mutate/InsertWithTimeType.feature
Labels: ready-for-testing

#874 Fix action can't run on centos6
  .github/actions/upload-assets-action/README.md
  .github/actions/upload-assets-action/action.yml
  .github/actions/upload-to-oss-action/README.md
  .github/actions/upload-to-oss-action/action.yml
  .github/workflows/package.yml
  .github/workflows/release.yml
Labels: ready-for-review, ready-for-testing

#825 Refactor the setup method of nebula servers in CI
  .github/workflows/pull_request.yml
  tests/.gitignore
  tests/Makefile
  tests/README.md
  tests/common/constants.py
  tests/common/global_data_loader.py
  tests/common/nebula_service.py
  tests/common/utils.py
  tests/conftest.py
  tests/nebula-test-run.py
  tests/pytest.ini
  tests/tck/conftest.py
Labels: ready-for-testing

#891 Fix bug: "desc space create_on_group" show true but not group_name
  src/executor/admin/SpaceExecutor.cpp
Labels: ready-for-testing

#890 Fix failures about `insert' test cases
  tests/tck/features/insert/Insert.IntVid.feature
  tests/tck/features/insert/Insert.feature
Labels: ready-for-testing

#886 Enable some skipped test cases
  tests/common/dataset_printer.py
  tests/pytest.ini
  tests/query/stateless/test_simple_query.py
  tests/tck/conftest.py
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/go/GroupbyLimit.IntVid.feature
  tests/tck/features/go/GroupbyLimit.feature
  tests/tck/features/insert/Insert.feature
  tests/tck/features/lookup/LookUp.IntVid.feature
  tests/tck/features/lookup/LookUp.feature
  tests/tck/features/match/StartFromAnyNode.IntVid.feature
  tests/tck/features/match/StartFromAnyNode.feature
Labels: ready-for-testing

#884 Update README.md
  README.md
Labels: ready-for-testing

#885 Update README-CN.md
  README-CN.md
Labels: ready-for-testing

#893 Fix version bug when packaging
  package/package.sh
  src/executor/query/GetVerticesExecutor.cpp
  tests/README.md
  tests/tck/features/mutate/InsertWithTimeType.feature
Labels: ready-for-testing

#894 replace multimap with unordered_multimap
  src/executor/algo/BFSShortestPathExecutor.cpp
Labels: ready-for-review, ready-for-testing

#897 Set thread manager for thrift server.
  src/daemons/GraphDaemon.cpp
Labels: ready-for-testing

#810 Push down some expressions to the storage layer
  src/util/ParserUtil.cpp
  src/visitor/ExtractFilterExprVisitor.cpp
  tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
Labels: ready-for-testing

#875 Add check to add listener hosts and test
  src/validator/AdminValidator.cpp
  tests/admin/test_listener.py
Labels: ready-for-testing

#870 refactor rewrite visitors
  src/executor/test/FilterTest.cpp
  src/planner/match/Expand.cpp
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/MatchSolver.cpp
  src/planner/match/MatchSolver.h
  src/planner/match/UnwindClausePlanner.cpp
  src/planner/match/WhereClausePlanner.cpp
  src/planner/match/WhereClausePlanner.h
  src/planner/match/YieldClausePlanner.cpp
  src/util/ExpressionUtils.h
  src/util/ParserUtil.cpp
  src/util/ParserUtil.h
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchVerticesValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/GoValidator.h
  src/validator/GroupByValidator.cpp
  src/validator/LookupValidator.cpp
  src/validator/MatchValidator.cpp
  src/visitor/CMakeLists.txt
  src/visitor/RewriteAggExprVisitor.cpp
  src/visitor/RewriteAggExprVisitor.h
  src/visitor/RewriteInputPropVisitor.cpp
  src/visitor/RewriteInputPropVisitor.h
  src/visitor/RewriteLabelAttrVisitor.cpp
  src/visitor/RewriteLabelAttrVisitor.h
  src/visitor/RewriteMatchLabelVisitor.cpp
  src/visitor/RewriteVisitor.cpp
  src/visitor/RewriteVisitor.h
Labels: ready-for-review, ready-for-testing

#898 Avoid null parameter.
  src/parser/parser.yy
Labels: ready-for-testing

#904 Fix unstable test cases related to index
  package/package.sh
  tests/maintain/test_index.py
  tests/maintain/test_zone.py
  tests/nebula-test-run.py
  tests/query/stateless/test_lookup.py
  tests/query/stateless/test_range.py
  tests/tck/conftest.py
  tests/tck/features/index/TagEdgeIndex.feature
  tests/tck/features/lookup/LookUp.feature
Labels: in progress, ready-for-testing

#804 build docker image of nebula-tools
  .github/workflows/release.yml
Labels: ready-for-testing
