Repository vesoft-inc/nebula-graph, pull requests merged in 2021-05, with the labels that each got.

#995 change QueryAstContext to CypherAstContext
  src/context/ast/CypherAstContext.h
  src/context/ast/QueryAstContext.h
  src/planner/match/CypherClausePlanner.h
  src/planner/match/Expand.h
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/MatchPlanner.cpp
  src/planner/match/MatchPlanner.h
  src/planner/match/MatchSolver.cpp
  src/planner/match/MatchSolver.h
  src/planner/match/SegmentsConnector.h
  src/planner/match/StartVidFinder.h
  src/planner/match/VertexIdSeek.h
  src/validator/MatchValidator.h
Labels: ready-for-testing

#985 small change pullAnds/pullOrs
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
Labels: ready-for-testing

#983 Feature/edge seek with range
  src/planner/match/LabelIndexSeek.cpp
  src/planner/match/PropIndexSeek.cpp
  tests/data/nba/config.yaml
  tests/data/nba_int_vid/config.yaml
  tests/tck/features/match/Base.IntVid.feature
  tests/tck/features/match/Base.feature
  tests/tck/features/match/SeekByEdge.feature
Labels: doc affected, ready-for-testing

#996 Add the case about that fetch not exists vertex/edge on *.
  tests/tck/features/fetch/FetchVertices.intVid.feature
  tests/tck/features/fetch/FetchVertices.strVid.feature
Labels: ready-for-testing

#997 Rename binary input plan node
  src/optimizer/OptGroup.cpp
  src/optimizer/Optimizer.cpp
  src/optimizer/rule/RemoveNoopProjectRule.cpp
  src/planner/Algo.cpp
  src/planner/Algo.h
  src/planner/PlanNode.cpp
  src/planner/PlanNode.h
  src/planner/Query.cpp
  src/planner/Query.h
  src/validator/SetValidator.cpp
  src/validator/test/ValidatorTestBase.cpp
Labels: ready-for-testing

#970 combine consecutive filter plan nodes
  src/optimizer/CMakeLists.txt
  src/optimizer/rule/CombineFilterRule.cpp
  src/optimizer/rule/CombineFilterRule.h
  tests/tck/features/expression/UnaryExpr.feature
  tests/tck/features/optimizer/CombineFilterRule.feature
  tests/tck/features/optimizer/MergeGetVerticesDedupProjectRule.feature
Labels: ready-for-testing

#895 Feature/comment
  src/executor/admin/SpaceExecutor.cpp
  src/executor/maintain/EdgeIndexExecutor.cpp
  src/executor/maintain/TagIndexExecutor.cpp
  src/parser/AdminSentences.cpp
  src/parser/AdminSentences.h
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/planner/Maintain.h
  src/util/IndexUtil.cpp
  src/util/SchemaUtil.cpp
  src/util/SchemaUtil.h
  src/validator/AdminValidator.cpp
  src/validator/MaintainValidator.cpp
  tests/admin/test_space.py
  tests/query/stateless/test_schema.py
  tests/tck/features/index/Index.feature
  tests/tck/features/schema/Comment.feature
  tests/tck/features/schema/Schema.feature
  tests/tck/features/ttl/TTL.feature
Labels: doc affected, ready-for-testing

#954 Fix alias check
  src/validator/MatchValidator.cpp
  src/validator/MatchValidator.h
  src/validator/test/MatchValidatorTest.cpp
Labels: ready-for-testing

#968 aggregate enhancement
  src/validator/GroupByValidator.cpp
  src/validator/GroupByValidator.h
  src/validator/MatchValidator.cpp
  tests/tck/features/aggregate/Agg.feature
Labels: enhancement, ready-for-testing

#976 Delete unused code of package.sh
  package/package.sh
Labels: ready-for-testing

#949 move util function to cpp file
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
Labels: ready-for-testing

#1004 fix tck parser error
  tests/common/plan_differ.py
Labels: ready-for-testing

#961 optimize header files
  src/context/ExecutionContext.h
  src/context/Iterator.h
  src/context/QueryContext.h
  src/context/QueryExpressionContext.cpp
  src/context/Result.h
  src/context/Symbols.h
  src/executor/Executor.h
  src/executor/query/GetNeighborsExecutor.h
  src/optimizer/OptimizerUtils.h
  src/parser/Clauses.cpp
  src/parser/EdgeKey.cpp
  src/parser/MaintainSentences.cpp
  src/parser/MatchSentence.h
  src/parser/MutateSentences.cpp
  src/parser/ProcessControlSentences.h
  src/parser/SequentialSentences.cpp
  src/parser/TraverseSentences.h
  src/parser/UserSentences.h
  src/planner/Algo.h
  src/planner/ExecutionPlan.h
  src/planner/Logic.h
  src/planner/Maintain.h
  src/planner/Mutate.h
  src/planner/PlanNode.h
  src/planner/Query.h
  src/scheduler/Scheduler.h
  src/service/CloudAuthenticator.cpp
  src/service/GraphFlags.cpp
  src/service/PasswordAuthenticator.h
  src/service/PermissionCheck.h
  src/service/QueryEngine.h
  src/service/QueryInstance.h
  src/service/Session.h
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/util/IndexUtil.h
  src/util/ParserUtil.h
  src/util/ZoneUtil.h
  src/validator/AdminJobValidator.h
  src/validator/AssignmentValidator.h
  src/validator/BalanceValidator.h
  src/validator/FetchEdgesValidator.h
  src/validator/FetchVerticesValidator.h
  src/validator/GetSubgraphValidator.h
  src/validator/GoValidator.h
  src/validator/LimitValidator.h
  src/validator/MaintainValidator.h
  src/validator/MutateValidator.h
  src/validator/OrderByValidator.h
  src/validator/PipeValidator.cpp
  src/validator/SequentialValidator.h
  src/validator/UseValidator.h
  src/validator/Validator.h
  src/validator/test/MockSchemaManager.h
Labels: ready-for-testing

#1001 Draft a rfc teamplate.
  .github/ISSUE_TEMPLATE/RFC.md
Labels: ready-for-testing

#1005 embed or-filter into IndexScan
  src/planner/match/LabelIndexSeek.cpp
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/util/test/ExpressionUtilsTest.cpp
  tests/tck/features/optimizer/IndexScanRule.feature
Labels: ready-for-testing

#744 Support to checkout the branch of module
  cmake/FetchModule.cmake
Labels: ready-for-testing

#903 Refactor lookup validator
  src/planner/match/MatchSolver.cpp
  src/util/ExpressionUtils.cpp
  src/validator/LookupValidator.cpp
  src/validator/LookupValidator.h
  src/validator/test/LookupValidatorTest.cpp
  tests/tck/features/lookup/ByIndex.feature
  tests/tck/features/lookup/ByIndex.intVid.feature
Labels: enhancement, ready-for-testing

#991 Add the subscript range expression.
  src/parser/parser.yy
  src/parser/test/ParserTest.cpp
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/DeduceTypeVisitor.h
  src/visitor/EvaluableExprVisitor.h
  src/visitor/ExprVisitorImpl.cpp
  src/visitor/ExprVisitorImpl.h
  src/visitor/ExtractFilterExprVisitor.cpp
  src/visitor/ExtractFilterExprVisitor.h
  src/visitor/FindVisitor.cpp
  src/visitor/FindVisitor.h
  src/visitor/FoldConstantExprVisitor.cpp
  src/visitor/FoldConstantExprVisitor.h
  src/visitor/RewriteSymExprVisitor.cpp
  src/visitor/RewriteSymExprVisitor.h
  src/visitor/RewriteVisitor.cpp
  src/visitor/RewriteVisitor.h
  src/visitor/VidExtractVisitor.cpp
  src/visitor/VidExtractVisitor.h
  tests/tck/conftest.py
  tests/tck/features/expression/ListRangeSubscript.feature
  tests/tck/openCypher/features/expressions/list/List2.feature
Labels: doc affected, ready-for-testing

#1010 Test pipe and sequential sentences for match
  tests/tck/features/match/PipeAndVariable.feature
Labels: ready-for-testing

#1015 fix #1012: Collect values from InputExpression crash the nebula graphd
  src/util/ExpressionUtils.cpp
  tests/tck/features/aggregate/Agg.feature
Labels: ready-for-testing

#1020 fix typo
  src/parser/AdminSentences.cpp
  src/validator/AdminJobValidator.h
Labels: depend on common, ready-for-testing

#1025 refactor getEdgesExecutor
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/GetEdgesExecutor.h
Labels: ready-for-testing

#1018 refactor unwind
  src/context/ast/CypherAstContext.h
  src/executor/query/UnwindExecutor.cpp
  src/executor/test/UnwindTest.cpp
  src/planner/match/LabelIndexSeek.cpp
  src/planner/match/MatchPlanner.cpp
  src/planner/match/PropIndexSeek.cpp
  src/planner/match/UnwindClausePlanner.cpp
  src/planner/plan/Query.cpp
  src/planner/plan/Query.h
  src/validator/MatchValidator.cpp
  tests/tck/features/match/Unwind.feature
  tests/tck/features/match/With.feature
Labels: ready-for-testing

#1023 Stop loop when expand to end.
  src/executor/query/DataCollectExecutor.cpp
  src/planner/match/Expand.cpp
  src/planner/match/Expand.h
  src/util/ExpressionUtils.h
  src/validator/GetSubgraphValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/TraversalValidator.cpp
  src/validator/TraversalValidator.h
  tests/tck/features/go/GO.IntVid.feature
  tests/tck/features/go/GO.feature
  tests/tck/features/match/VariableLengthPattern.feature
  tests/tck/features/match/VariableLengthPattern.intVid.feature
Labels: ready-for-testing

#1036 Stop expand when reach end for subgraph.
  src/validator/GetSubgraphValidator.cpp
  tests/tck/features/subgraph/subgraph.IntVid.feature
  tests/tck/features/subgraph/subgraph.feature
Labels: doc affected, incompatible, ready-for-testing

#1022 only for removing kvstore::resultCode
  src/executor/StorageAccessExecutor.h
  tests/tck/features/schema/Schema.feature
  tests/tck/features/user/User.feature
Labels: ready-for-testing

#905 Group default conflict check
  src/parser/AdminSentences.h
  src/validator/AdminValidator.cpp
  src/validator/MaintainValidator.cpp
  tests/admin/test_space.py
  tests/maintain/test_zone.py
Labels: ready-for-testing

#928 Rewrite relational expression
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/validator/LookupValidator.cpp
  src/validator/MaintainValidator.cpp
  src/validator/MatchValidator.cpp
  src/validator/YieldValidator.cpp
  src/visitor/test/CMakeLists.txt
  src/visitor/test/FilterTransformTest.cpp
  src/visitor/test/FoldConstantExprVisitorTest.cpp
  src/visitor/test/RewriteRelExprVisitorTest.cpp
  src/visitor/test/VisitorTestBase.h
  tests/tck/features/expression/RelationalExpr.feature
  tests/tck/features/expression/UnaryExpr.feature
  tests/tck/features/match/SeekById.intVid.feature
Labels: ready-for-testing

#1002 add variableDependencyNode
  src/context/ast/QueryAstContext.h
  src/executor/query/DataCollectExecutor.cpp
  src/executor/test/DataCollectTest.cpp
  src/planner/SequentialPlanner.cpp
  src/planner/plan/PlanNode.cpp
  src/planner/plan/PlanNode.h
  src/planner/plan/Query.cpp
  src/planner/plan/Query.h
  src/validator/FindPathValidator.cpp
  src/validator/GetSubgraphValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/test/FetchEdgesTest.cpp
  src/validator/test/FetchVerticesTest.cpp
  src/validator/test/ValidatorTestBase.cpp
Labels: ready-for-testing

#1042 fix ci test error
  tests/tck/features/update/Update.feature
Labels: ready-for-testing

#1044 move getVertexProp to util
  src/planner/match/MatchSolver.cpp
  src/planner/match/MatchSolver.h
  src/util/SchemaUtil.cpp
  src/util/SchemaUtil.h
Labels: ready-for-testing

#1045 fix ci test error again
  tests/admin/test_permission.py
  tests/common/nebula_test_suite.py
  tests/job/test_jobs.py
  tests/query/stateless/test_range.py
  tests/tck/conftest.py
  tests/tck/features/update/Update.feature
Labels: ready-for-testing

#1035 move condition to util
  src/planner/match/Expand.cpp
  src/planner/match/Expand.h
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
Labels: ready-for-testing

#1027 datacollect pathprop
  src/executor/query/DataCollectExecutor.cpp
  src/executor/query/DataCollectExecutor.h
  src/executor/test/DataCollectTest.cpp
  src/planner/plan/Query.cpp
  src/planner/plan/Query.h
Labels: ready-for-testing

#1013 Add more pipe test cases for match and go
  tests/tck/features/aggregate/Agg.feature
  tests/tck/features/match/PipeAndVariable.feature
Labels: ready-for-testing

#1048 [Simple] Add test case from issue
  tests/tck/features/go/GO.feature
Labels: ready-for-testing

#1021 Remove the useless condition check.
  src/service/SessionManager.cpp
Labels: ready-for-testing

#1050 [Simple] Add test case from issue
  tests/tck/features/match/MatchById.IntVid.feature
  tests/tck/features/match/MatchById.feature
Labels: ready-for-testing

#1047 fix ci test error thrid
  tests/tck/features/index/Index.IntVid.feature
  tests/tck/features/update/Update.IntVid.feature
Labels: ready-for-testing

#1026 add path with prop test case
  tests/tck/features/path/AllPath.IntVid.feature
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/NoLoop.IntVid.feature
  tests/tck/features/path/NoLoop.feature
  tests/tck/features/path/ShortestPath.IntVid.feature
  tests/tck/features/path/ShortestPath.feature
Labels: ready-for-testing

#1051 optimizer: add PushFilterDownProjectRule
  src/optimizer/CMakeLists.txt
  src/optimizer/rule/PushFilterDownProjectRule.cpp
  src/optimizer/rule/PushFilterDownProjectRule.h
  tests/tck/features/optimizer/PushFilterDownProjectRule.feature
Labels: ready-for-testing

#1049 push Filter down LeftJoin
  src/optimizer/CMakeLists.txt
  src/optimizer/rule/PushFilterDownLeftJoinRule.cpp
  src/optimizer/rule/PushFilterDownLeftJoinRule.h
  src/planner/plan/Query.h
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/util/test/ExpressionUtilsTest.cpp
  src/validator/GoValidator.cpp
  src/validator/GoValidator.h
  tests/tck/features/optimizer/PushFilterDownLeftJoinRule.feature
Labels: ready-for-testing

#1073 fix user defined var
  .github/workflows/pull_request.yml
  src/validator/YieldValidator.cpp
Labels: ready-for-testing

#1067 Check memory usage before starting executor
  conf/nebula-graphd.conf.default
  conf/nebula-graphd.conf.production
  resources/gflags.json
  src/executor/Executor.cpp
  src/service/GraphFlags.cpp
  src/service/GraphFlags.h
  tests/admin/test_configs.py
Labels: ready-for-testing

#1037 Support specified columns for full-text index
  src/executor/CMakeLists.txt
  src/executor/Executor.cpp
  src/executor/admin/SpaceExecutor.cpp
  src/executor/maintain/FTIndexExecutor.cpp
  src/executor/maintain/FTIndexExecutor.h
  src/parser/MaintainSentences.cpp
  src/parser/MaintainSentences.h
  src/parser/Sentence.h
  src/parser/parser.yy
  src/parser/scanner.lex
  src/planner/plan/Maintain.cpp
  src/planner/plan/Maintain.h
  src/planner/plan/PlanNode.cpp
  src/planner/plan/PlanNode.h
  src/service/PermissionCheck.cpp
  src/util/CMakeLists.txt
  src/util/FTIndexUtils.cpp
  src/util/FTIndexUtils.h
  src/validator/LookupValidator.cpp
  src/validator/LookupValidator.h
  src/validator/MaintainValidator.cpp
  src/validator/MaintainValidator.h
  src/validator/Validator.cpp
  src/validator/test/MockSchemaManager.h
Labels: depend on common, depend on storage, doc affected, ready-for-testing

#1070 Enhance pushFilterDownProj
  src/optimizer/rule/PushFilterDownAggregateRule.cpp
  src/optimizer/rule/PushFilterDownLeftJoinRule.cpp
  src/optimizer/rule/PushFilterDownProjectRule.cpp
  src/planner/plan/Query.h
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/validator/YieldValidator.cpp
  tests/tck/features/optimizer/CombineFilterRule.feature
Labels: ready-for-testing

#1078 Fix the setter of input of join.
  src/planner/plan/Query.h
Labels: bug, ready-for-testing

#944 Show version in host.
  src/context/test/CMakeLists.txt
  src/executor/admin/ShowHostsExecutor.cpp
  src/executor/test/CMakeLists.txt
  src/optimizer/test/CMakeLists.txt
  src/parser/test/CMakeLists.txt
  src/util/test/CMakeLists.txt
  src/validator/test/CMakeLists.txt
  src/visitor/test/CMakeLists.txt
  tests/tck/features/admin/Hosts.feature
Labels: depend on common, doc affected, hi-pri, ready-for-testing

#1084 Allow executors continue to run except query type plan node
  src/executor/Executor.cpp
  src/planner/plan/PlanNode.h
Labels: ready-for-testing

#1040 refactor path
  src/context/ast/QueryAstContext.h
  src/executor/algo/CartesianProductExecutor.cpp
  src/executor/algo/ConjunctPathExecutor.cpp
  src/executor/query/DataCollectExecutor.cpp
  src/executor/query/DataCollectExecutor.h
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/UnwindExecutor.cpp
  src/executor/test/ConjunctPathTest.cpp
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/planner/CMakeLists.txt
  src/planner/PlannersRegister.cpp
  src/planner/PlannersRegister.h
  src/planner/ngql/PathPlanner.cpp
  src/planner/ngql/PathPlanner.h
  src/planner/plan/Query.cpp
  src/planner/plan/Query.h
  src/util/AnonColGenerator.h
  src/util/CMakeLists.txt
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  src/util/QueryUtil.cpp
  src/util/QueryUtil.h
  src/validator/FindPathValidator.cpp
  src/validator/FindPathValidator.h
  src/validator/GetSubgraphValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/MatchValidator.h
  src/validator/TraversalValidator.cpp
  src/validator/TraversalValidator.h
  src/validator/Validator.h
  src/validator/test/FindPathValidatorTest.cpp
  tests/tck/features/path/AllPath.IntVid.feature
  tests/tck/features/path/AllPath.feature
  tests/tck/features/path/NoLoop.IntVid.feature
  tests/tck/features/path/NoLoop.feature
  tests/tck/features/path/ShortestPath.IntVid.feature
  tests/tck/features/path/ShortestPath.feature
Labels: ready-for-testing

#1069 fix rand in agg
  src/parser/parser.yy
  src/util/ExpressionUtils.cpp
  src/util/ExpressionUtils.h
  tests/tck/features/yield/return.feature
  tests/tck/features/yield/yield.feature
Labels: bug, ready-for-testing

#1088 Modify add_system_memory_high_watermark_ratio when test
  src/planner/plan/PlanNode.h
  tests/admin/test_configs.py
  tests/common/nebula_service.py
Labels: ready-for-testing

#1072 Add the cmake option to checkout modules.
  CMakeLists.txt
  cmake/FetchModule.cmake
Labels: ready-for-testing

#1089 Modify some tck tests
  tests/tck/features/index/Index.feature
  tests/tck/features/lookup/LookUp.IntVid.feature
Labels: ready-for-testing

#982 Cleanup expression std::string arguments usage
  src/context/ast/CypherAstContext.h
  src/executor/test/AggregateTest.cpp
  src/executor/test/AssignTest.cpp
  src/executor/test/GetNeighborsTest.cpp
  src/executor/test/JoinTest.cpp
  src/executor/test/LogicExecutorsTest.cpp
  src/optimizer/rule/IndexScanRule.cpp
  src/optimizer/rule/MergeGetNbrsAndProjectRule.cpp
  src/optimizer/rule/MergeGetVerticesAndProjectRule.cpp
  src/optimizer/rule/PushFilterDownAggregateRule.cpp
  src/optimizer/rule/PushFilterDownLeftJoinRule.cpp
  src/optimizer/rule/PushFilterDownProjectRule.cpp
  src/optimizer/rule/RemoveNoopProjectRule.cpp
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/parser/MatchSentence.cpp
  src/parser/MatchSentence.h
  src/parser/parser.yy
  src/parser/test/ExpressionParsingTest.cpp
  src/planner/match/Expand.cpp
  src/planner/match/LabelIndexSeek.cpp
  src/planner/match/MatchClausePlanner.cpp
  src/planner/match/MatchSolver.cpp
  src/planner/match/PropIndexSeek.cpp
  src/planner/match/VertexIdSeek.cpp
  src/planner/ngql/PathPlanner.cpp
  src/util/ExpressionUtils.cpp
  src/util/FTIndexUtils.cpp
  src/util/ParserUtil.cpp
  src/util/QueryUtil.cpp
  src/validator/FetchEdgesValidator.cpp
  src/validator/FetchVerticesValidator.cpp
  src/validator/GetSubgraphValidator.cpp
  src/validator/GoValidator.cpp
  src/validator/GroupByValidator.cpp
  src/validator/LookupValidator.cpp
  src/validator/MatchValidator.cpp
  src/validator/MatchValidator.h
  src/validator/MutateValidator.cpp
  src/validator/OrderByValidator.cpp
  src/validator/TraversalValidator.cpp
  src/validator/Validator.cpp
  src/validator/YieldValidator.cpp
  src/validator/test/FetchEdgesTest.cpp
  src/validator/test/FetchVerticesTest.cpp
  src/visitor/DeducePropsVisitor.cpp
  src/visitor/DeduceTypeVisitor.cpp
  src/visitor/ExtractPropExprVisitor.cpp
  src/visitor/FoldConstantExprVisitor.cpp
  src/visitor/RewriteSymExprVisitor.cpp
  src/visitor/VidExtractVisitor.cpp
  src/visitor/test/VisitorTestBase.h
Labels: ready-for-testing

#1095 Cleanup plan node colNamesRef function
  src/executor/query/GetEdgesExecutor.cpp
  src/executor/query/GetVerticesExecutor.cpp
  src/executor/query/IndexScanExecutor.cpp
  src/planner/match/InnerJoinStrategy.cpp
  src/planner/match/MatchClausePlanner.cpp
  src/planner/plan/PlanNode.h
  src/validator/test/ValidatorTestBase.cpp
Labels: depend on common, ready-for-testing

#1094 Shrink sizeof Value struct
  src/optimizer/OptimizerUtils.cpp
  src/optimizer/test/IndexBoundValueTest.cpp
Labels: ready-for-testing

#1074 Fix expression raw string interface usage
  src/parser/Clauses.cpp
  src/parser/Clauses.h
  src/util/ParserUtil.cpp
  src/validator/MatchValidator.cpp
  src/validator/MutateValidator.cpp
  src/validator/Validator.cpp
  tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
Labels: depend on common, ready-for-testing, wip
